### ISSUE TITLE
Volume up/down in "Volumes" section

### ISSUE THREAD

**Issue by davidvasil** [punxaphil/custom-sonos-card#156]
**Is your feature request related to a problem? Please describe.**
I love having the volume up/down buttons back, I like to have more precise control over what volume my speakers are set to and have trouble with doing that via slider.  

It does not look like the up/down buttons were added to the "Volumes" section of the card though, so it is not possible to control individual speaker volumes when grouped.

**Describe the solution you'd like**
Add the up/down volume buttons to the volume slider in the "Volumes" card section.

**Describe alternatives you've considered**
Just use the slider to control volumes when speakers are grouped.

**Additional context**

**Comment by johanfrick** [comment]
Thanks for reporting. I'll add it to my list of todo:s.

**Comment by johanfrick** [comment]
Fixed in [v6.4.1](https://github.com/johanfrick/custom-sonos-card/releases/tag/v6.4.1)
