### ISSUE TITLE
>=v6.12.0 doesn't load on Samsung Smartfridge browser

### ISSUE THREAD

**Issue by snairolf** [punxaphil/custom-sonos-card#238]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**
Does not load on Samsung smart fridge browser.

**Last working release (if known):**
v6.11.3

**Browser and Operating System:**
Samsung Smart fridge (Tizen browser 1.0; seems to be running webkit 537.36)

This may be a similar issues as described here (which also occurs on this browser): https://www.reddit.com/r/homeassistant/comments/ly3xw9/cardmod_v30_is_not_working_for_me/

**Description of problem:**

Getting error: "Custom element doesn't exist: sonos-card."

**Reproduce**

* Firefox 70.0 w/ webkit 537.36
* Error: SyntaxError: expected expression, got '?'
 [custom-sonos-card.js:12:625]

**Comment by johanfrick** [comment]
Thanks for reporting. I'm afraid I won't be able to solve that issue on my own, but I have tagged it with "help wanted" so fingers crossed someone else have any ideas.

**Comment by snairolf** [comment]
I updated some details about how I am able to reproduce it.

**Comment by johanfrick** [comment]
I have reproduced the error in Firefox 70, but unfortunately that error message doesn't help me anything. If you have a suggestion for a specific fix for it, please let me know.

**Comment by MD1508** [comment]
I have the same Problem as snairolf

**Comment by snairolf** [comment]
I think as of 6.14.9 (or before) this has been fixed for me.

**Comment by MD1508** [comment]
I have installed the actual version and have still the problem on my Samsung fridge Am 11.01.2024 um 03:29 schrieb Rolf S ***@***.***>:﻿
I think as of 6.14.9 (or before) this has been fixed for me.

**Comment by johanfrick** [comment]
Could you test this beta release and see if the issue remains? 

**[v7-alpha](https://github.com/johanfrick/custom-sonos-card/releases/tag/v7-alpha)**

🚀 Features
[feature: indicate if no supported players are found](https://github.com/johanfrick/custom-sonos-card/commit/14facd0612a0f82d8094965c35247d6afa0c9e0b)
[feature: indicate if no favorites are found](https://github.com/johanfrick/custom-sonos-card/commit/969d6c71452047c9a650ef4588d68531355ff291)
[feature: show players that does not have grouping support](https://github.com/johanfrick/custom-sonos-card/commit/840b516de817e56ca9bae5e192875d8822a34b2f)
[feature: when grouping use apply button to avoid calling server on every selection](https://github.com/johanfrick/custom-sonos-card/commit/d16686149df7da564cf6bbe4770d06f38e3aa9fc)
[feature: show volume in grouping](https://github.com/johanfrick/custom-sonos-card/commit/c4b0e82891673072f55c9d6c3b1958a3beeb9063)
[feature: keep events internal to single card as much as possible](https://github.com/johanfrick/custom-sonos-card/commit/9b073a7db9b3975618e564163601b121fb6d2a9f)
[feature: make it possible to only show sonos players](https://github.com/johanfrick/custom-sonos-card/commit/4765e7c8cc1b8a9d6936b06c6290172a86469187)
[feature: make it possible to override fallback artwork image in player section](https://github.com/johanfrick/custom-sonos-card/commit/4d1cfa1e29fb016d015b8a0ac817b229b459ee12)
[feature: allow to ignore volume level for certain players in the player section](https://github.com/johanfrick/custom-sonos-card/commit/abd02fbf53e66613656a8d3fca9d7416f2a813e9)
[feature: allow non-sonos players in the visual editor](https://github.com/johanfrick/custom-sonos-card/commit/f6fce6235d254b6845c6b38279d7d13f5059e0f2)
🐛 Fixes
[fix: only use main player to get favorites](https://github.com/johanfrick/custom-sonos-card/commit/a684bd2a97e4633340d3bb2bdc685b3fbb07ef1c)
[fix: hide volume control if player is idle](https://github.com/johanfrick/custom-sonos-card/commit/3924e8ddf9d578367bf33c29589df469e43dc534)
[fix: "no media selected" not always showing correctly](https://github.com/johanfrick/custom-sonos-card/commit/0479414756118dfd8333e77ff8ba22bb4a0f5cea)

**Comment by punxaphil** [comment]
No response. Closing.

**Comment by farstreet** [comment]
I'm afraid that the issue still isn't solved.   With the latest version (7.1.2), I still get the attached error.
![tempImagen04nJH](https://github.com/punxaphil/custom-sonos-card/assets/24705229/097d10c6-c8a4-42ef-a59b-55c511efcf62)

**Comment by punxaphil** [comment]
Yeah, assumed so. No idea how to solve it though.

**Comment by xArorAx** [comment]
I have the same issue on Google Nest Hub Max
