### ISSUE TITLE
Cover picture missing when casting

### ISSUE THREAD

**Issue by Thomsen-79** [punxaphil/custom-sonos-card#271]
- [x] I updated to the latest version available *yes*
- [x] I cleared the cache of my browser *yes*

**Release with the issue:** latest*

**Last working release (if known):**dont know*

**Browser and Operating System:** Home assistant 11.4 on rpi 4*

**Description of problem:**when casting the Dashboard with nabu casa (in my case to a google nest hub max) with the sonos card I can in the right column see the cover pics, but when its played it dont show in the “player” sektion.*
![IMG_8311](https://github.com/johanfrick/custom-sonos-card/assets/61097896/d60d4dc9-2dc8-4ffe-bb4a-8e516a93f53a)

**Comment by johanfrick** [comment]
Yes those images use different kind of URL:s and it is not something I can control as a card developer.
The ones on the right are public URLs, such as:
`https://i.scdn.co/image/ab67616d0000b2733ec130c06ae2a96540e237b9`
The ones in the player have this format:
`/api/media_player_proxy/media_player.spotify_cewan?token=509f7a5cd69d6aed967fa3a4ca20fef9b9a2d8016f4637cf82e458c80a142e25&cache=65636222436bb103`

So as you see the ones in the player are local URLs pointing to an image on your own Home Assistant server. You probably need to investigate why your Google Nest Hub Max cannot access images on your Home Assistant server.

**Comment by punxaphil** [comment]
Should be fixed in https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.0.0 with [fix: make http-2-https configurable for thumbnails](https://github.com/punxaphil/custom-sonos-card/commit/819437ecdb5e8c158f0a28ad8451b5b138cc9400)
