### ISSUE TITLE
Sonos Card does not find all Sonos devices

### ISSUE THREAD

**Issue by ARM-Mac** [punxaphil/custom-sonos-card#272]
**Checklist:**

- [ √] I updated to the latest version available
- [ √] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**
mac OS Sonoma, Safari Version 17.2.1 (19617.1.17.11.12)

Istalled is HA on an Debian 12 as Supervisor

**Description of problem:**
Only 4 devices are found, although the Sonos integration shows all the devices that are missing here. 
What am I doing wrong?

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by johanfrick** [comment]
Could you test this beta release and see if the issue remains? 

**[v7-alpha](https://github.com/johanfrick/custom-sonos-card/releases/tag/v7-alpha)**

🚀 Features
[feature: indicate if no supported players are found](https://github.com/johanfrick/custom-sonos-card/commit/14facd0612a0f82d8094965c35247d6afa0c9e0b)
[feature: indicate if no favorites are found](https://github.com/johanfrick/custom-sonos-card/commit/969d6c71452047c9a650ef4588d68531355ff291)
[feature: show players that does not have grouping support](https://github.com/johanfrick/custom-sonos-card/commit/840b516de817e56ca9bae5e192875d8822a34b2f)
[feature: when grouping use apply button to avoid calling server on every selection](https://github.com/johanfrick/custom-sonos-card/commit/d16686149df7da564cf6bbe4770d06f38e3aa9fc)
[feature: show volume in grouping](https://github.com/johanfrick/custom-sonos-card/commit/c4b0e82891673072f55c9d6c3b1958a3beeb9063)
[feature: keep events internal to single card as much as possible](https://github.com/johanfrick/custom-sonos-card/commit/9b073a7db9b3975618e564163601b121fb6d2a9f)
[feature: make it possible to only show sonos players](https://github.com/johanfrick/custom-sonos-card/commit/4765e7c8cc1b8a9d6936b06c6290172a86469187)
[feature: make it possible to override fallback artwork image in player section](https://github.com/johanfrick/custom-sonos-card/commit/4d1cfa1e29fb016d015b8a0ac817b229b459ee12)
[feature: allow to ignore volume level for certain players in the player section](https://github.com/johanfrick/custom-sonos-card/commit/abd02fbf53e66613656a8d3fca9d7416f2a813e9)
[feature: allow non-sonos players in the visual editor](https://github.com/johanfrick/custom-sonos-card/commit/f6fce6235d254b6845c6b38279d7d13f5059e0f2)
🐛 Fixes
[fix: only use main player to get favorites](https://github.com/johanfrick/custom-sonos-card/commit/a684bd2a97e4633340d3bb2bdc685b3fbb07ef1c)
[fix: hide volume control if player is idle](https://github.com/johanfrick/custom-sonos-card/commit/3924e8ddf9d578367bf33c29589df469e43dc534)
[fix: "no media selected" not always showing correctly](https://github.com/johanfrick/custom-sonos-card/commit/0479414756118dfd8333e77ff8ba22bb4a0f5cea)

**Comment by punxaphil** [comment]
Should be fixed by https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.0.0. Re-open if you still see the issue.
