### ISSUE TITLE
All Volume Slider at 100% When Primary Source is Fixed

### ISSUE THREAD

**Issue by rmbeatty** [punxaphil/custom-sonos-card#274]
I noticed that when the primary Sonos player has a fixed volume, the All Volume slider is at 100% not allowing you to globally adjust the remaining players that are not fixed.  Is there a way to ignore the fixed source?

**Comment by rmbeatty** [comment]
@johanfrick is this something you can help with?

**Comment by johanfrick** [comment]
What kind of sonos player is that? having a fixed volume

**Comment by johanfrick** [comment]
Why not just make some other speaker the master?

**Comment by johanfrick** [comment]
I wonder if this can be detected.
Can you go in to developer section then screen shot the full state with attributes for the Sonos port?

**Comment by rmbeatty** [comment]
Doesn't appear to be, other than seeing that volume level is 1 (100%) but that could be just someone playing it at full volume.  The setting to choose fixed or variable volume for this device is in the Sonos App or Desktop Controller.

![image](https://github.com/johanfrick/custom-sonos-card/assets/75537913/869adca3-9220-46aa-b52a-4f905fe1f778)

**Comment by johanfrick** [comment]
Go to templates and paste this

{{ states.media_player.hall.attributes }}

**Comment by rmbeatty** [comment]
Here you go.  Don't see anything here either..

{'source_list': ['Line-in'], 'group_members': ['media_player.living_room_sonos'], 'volume_level': 1.0, 'is_volume_muted': False, 'media_content_id': 'x-sonosapi-hls:Api%3atune%3aliveAudio%3apurejazz%3ae6333906-2e89-6c07-59d6-36d09248b8dc?sid=37&flags=288&sn=2', 'media_content_type': <MediaType.MUSIC: 'music'>, 'media_title': '67 - Real Jazz • Horace Silver/Jazz Messengers-The Preacher', 'media_channel': '67 - Real Jazz • Horace Silver/Jazz Messengers-The Preacher', 'shuffle': False, 'repeat': <RepeatMode.OFF: 'off'>, 'queue_position': 1, 'queue_size': 1, 'device_class': 'speaker', 'entity_picture': '/api/media_player_proxy/media_player.living_room_sonos?token=ea6e4e7bed276fd7d4b3ab96e91642afc9aaec33982b1d4e3ddcd5c3bdbe8074&cache=43bc0ed127342246', 'friendly_name': 'Living Room', 'supported_features': <MediaPlayerEntityFeature.PAUSE|SEEK|VOLUME_SET|VOLUME_MUTE|PREVIOUS_TRACK|NEXT_TRACK|PLAY_MEDIA|SELECT_SOURCE|STOP|CLEAR_PLAYLIST|PLAY|SHUFFLE_SET|BROWSE_MEDIA|REPEAT_SET|GROUPING|MEDIA_ANNOUNCE|MEDIA_ENQUEUE: 4127295>}

**Comment by johanfrick** [comment]
Yeah that didn't help. So what kind of logic are you looking for?

**Comment by johanfrick** [comment]
Could you test this beta release and see if it is a suitable solution? There is a new config `entitiesToIgnoreVolumeLevelFor`. 

**[v7-alpha](https://github.com/johanfrick/custom-sonos-card/releases/tag/v7-alpha)**

🚀 Features
[feature: indicate if no supported players are found](https://github.com/johanfrick/custom-sonos-card/commit/14facd0612a0f82d8094965c35247d6afa0c9e0b)
[feature: indicate if no favorites are found](https://github.com/johanfrick/custom-sonos-card/commit/969d6c71452047c9a650ef4588d68531355ff291)
[feature: show players that does not have grouping support](https://github.com/johanfrick/custom-sonos-card/commit/840b516de817e56ca9bae5e192875d8822a34b2f)
[feature: when grouping use apply button to avoid calling server on every selection](https://github.com/johanfrick/custom-sonos-card/commit/d16686149df7da564cf6bbe4770d06f38e3aa9fc)
[feature: show volume in grouping](https://github.com/johanfrick/custom-sonos-card/commit/c4b0e82891673072f55c9d6c3b1958a3beeb9063)
[feature: keep events internal to single card as much as possible](https://github.com/johanfrick/custom-sonos-card/commit/9b073a7db9b3975618e564163601b121fb6d2a9f)
[feature: make it possible to only show sonos players](https://github.com/johanfrick/custom-sonos-card/commit/4765e7c8cc1b8a9d6936b06c6290172a86469187)
[feature: make it possible to override fallback artwork image in player section](https://github.com/johanfrick/custom-sonos-card/commit/4d1cfa1e29fb016d015b8a0ac817b229b459ee12)
[feature: allow to ignore volume level for certain players in the player section](https://github.com/johanfrick/custom-sonos-card/commit/abd02fbf53e66613656a8d3fca9d7416f2a813e9)
[feature: allow non-sonos players in the visual editor](https://github.com/johanfrick/custom-sonos-card/commit/f6fce6235d254b6845c6b38279d7d13f5059e0f2)
🐛 Fixes
[fix: only use main player to get favorites](https://github.com/johanfrick/custom-sonos-card/commit/a684bd2a97e4633340d3bb2bdc685b3fbb07ef1c)
[fix: hide volume control if player is idle](https://github.com/johanfrick/custom-sonos-card/commit/3924e8ddf9d578367bf33c29589df469e43dc534)
[fix: "no media selected" not always showing correctly](https://github.com/johanfrick/custom-sonos-card/commit/0479414756118dfd8333e77ff8ba22bb4a0f5cea)

**Comment by punxaphil** [comment]
Fixed in https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.0.0
