### ISSUE TITLE
Sonos Card no longer working on Android Tablets

### ISSUE THREAD

**Issue by Jasonrobot00** [punxaphil/custom-sonos-card#283]
I have multiple Android Screens running android 11. I believe it was after the companion app update the Sonos card on the app stopped working. 

The Card does not load and says that the custom element cannot be found, I have taken multiple steps to try get around this from downloading an earlier version downloading the card manually placing the resources in multiple places. The card continues to work on my IOS App and computer and even on a browser page on the android tablet. 

Has anyone else experienced this? Are the developers aware?

**Comment by robotsmarthomes** [comment]
Hi, anyway to fix this? 

Please 🙏

**Comment by johanfrick** [comment]
I doubt it is a bug with this card. Since the custom element won't even load. Are other custom cards working?

**Comment by robotsmarthomes** [comment]
That’s so strange. It’s working on every other type of device except an android 11 screen that we use.  All other custom cards are working, we use cards like custom button card, my slider, card mod, bubble card. 

I really think it came up when the android app was updated in December

**Comment by johanfrick** [comment]
I fail to reproduce this. Card works on all of these for me:
- pixel 2, android 11
- Galaxy tab a8, android 13
- iPhones, iOS 
- chrome desktop

Please share your exact versions of the card and of the haos

**Comment by johanfrick** [comment]
@Jasonrobot00 @robotsmarthomes 
Can you try and clear cache? since it is working fine for me on Android 11.
[D](https://community.home-assistant.io/t/anyone-know-how-to-clear-cache-in-the-ios-app/64569/21)
If clearing cache doesn't. Maybe export log files in that page above. Anything there?

**Comment by johanfrick** [comment]
Could you test this beta release and see if the issue remains? 

**[v7-alpha](https://github.com/johanfrick/custom-sonos-card/releases/tag/v7-alpha)**

🚀 Features
[feature: indicate if no supported players are found](https://github.com/johanfrick/custom-sonos-card/commit/14facd0612a0f82d8094965c35247d6afa0c9e0b)
[feature: indicate if no favorites are found](https://github.com/johanfrick/custom-sonos-card/commit/969d6c71452047c9a650ef4588d68531355ff291)
[feature: show players that does not have grouping support](https://github.com/johanfrick/custom-sonos-card/commit/840b516de817e56ca9bae5e192875d8822a34b2f)
[feature: when grouping use apply button to avoid calling server on every selection](https://github.com/johanfrick/custom-sonos-card/commit/d16686149df7da564cf6bbe4770d06f38e3aa9fc)
[feature: show volume in grouping](https://github.com/johanfrick/custom-sonos-card/commit/c4b0e82891673072f55c9d6c3b1958a3beeb9063)
[feature: keep events internal to single card as much as possible](https://github.com/johanfrick/custom-sonos-card/commit/9b073a7db9b3975618e564163601b121fb6d2a9f)
[feature: make it possible to only show sonos players](https://github.com/johanfrick/custom-sonos-card/commit/4765e7c8cc1b8a9d6936b06c6290172a86469187)
[feature: make it possible to override fallback artwork image in player section](https://github.com/johanfrick/custom-sonos-card/commit/4d1cfa1e29fb016d015b8a0ac817b229b459ee12)
[feature: allow to ignore volume level for certain players in the player section](https://github.com/johanfrick/custom-sonos-card/commit/abd02fbf53e66613656a8d3fca9d7416f2a813e9)
[feature: allow non-sonos players in the visual editor](https://github.com/johanfrick/custom-sonos-card/commit/f6fce6235d254b6845c6b38279d7d13f5059e0f2)
🐛 Fixes
[fix: only use main player to get favorites](https://github.com/johanfrick/custom-sonos-card/commit/a684bd2a97e4633340d3bb2bdc685b3fbb07ef1c)
[fix: hide volume control if player is idle](https://github.com/johanfrick/custom-sonos-card/commit/3924e8ddf9d578367bf33c29589df469e43dc534)
[fix: "no media selected" not always showing correctly](https://github.com/johanfrick/custom-sonos-card/commit/0479414756118dfd8333e77ff8ba22bb4a0f5cea)

**Comment by robotsmarthomes** [comment]
Hello,

We have currently 'v7-alpha-2'. 

Still not working. 

Woiuld you like me to use v7-alpha?

**Comment by johanfrick** [comment]
Did you try clearing the cache as I posted earlier?

**Comment by robotsmarthomes** [comment]
Yes i cleared the cache. ah so strange!

**Comment by johanfrick** [comment]
Not sure how to debug this. I can't find any documentation from Home Assistant on how to debug frontend errors in the Companion App.
Anyway, can you try the "export logs"? It is only for server logs I believe, but if we are lucky something shows up there.

**Comment by robotsmarthomes** [comment]
I know this is a stretch. But could this be a contributing factor, 

There's a file called "/hacs.hacs and inside it:

{
  "version": "6",
  "minor_version": 1,
  "key": "hacs.hacs",
  "data": {
    "archived_repositories": [],
    "renamed_repositories": {
      "johanfrick/custom-sonos-card": "punxaphil/custom-sonos-card"
    },
    "ignored_repositories": []
  }
}

**Comment by robotsmarthomes** [comment]
Could it also be:

- Now since recent updates HA now is in "/homeassistant/www/community/custom-sonos-card/custom-sonos-card.js" - Previously it was /config/www/community/custom-sonos-card/custom-sonos-card.js
Possibly?

**Comment by punxaphil** [comment]
No idea actually. It seems it is something with your setup. The card works for pretty much everyone else.
Boring suggestions... but:
* Uninstall the card, and make sure there is no files left related to it
* Uninstalling HACS and make sure there are no remaining files for HACS. The reinstall again.
* try with a fresh install of Home Assistant

**Comment by swisslb** [comment]
I have exactly the same problem on my Samsung fridge with an Android screen. Trying to find a solution. I tried to unistall + reboot, not success. It's not an isolated case. Thanks a lot.

**Comment by punxaphil** [comment]
Don’t know what to do. I can’t reproduce it on my devices.

**Comment by tomik671108** [comment]
Most likely you have an old version of Android WebView on your device, I had the same thing on a tablet with Android 11, I had version 93 and the same symptoms.
Update Android WebView to the current version, from what I've read Home Assistant currently recommends a minimum version of 115.
Update Chrome, it should automatically update WebView
