### ISSUE TITLE
Volume step 1 or 2

### ISSUE THREAD

**Issue by sanderlv** [punxaphil/custom-sonos-card#289]
Hi, using the bar I can select any volume value, 2,3,4,5,6. But "up and down" always skip 2, so e.g. 2,4,6 or 3,5,7.

Is there an option to skip 1 with the volume buttons? It's now pretty hard to slide to 1 step up.

**Comment by johanfrick** [comment]
Unfortunately not. The  media player integration doesn't support setting the step size: https://www.home-assistant.io/integrations/media_player.
Feel free to request it from the people maintaining that integration.

**Comment by johanfrick** [comment]
Giving it a second thought, the volume_set can be used for this. Please try the below beta version that has this feature. Try with `volumeStepSize: 1`.
[v7-beta-3](https://github.com/johanfrick/custom-sonos-card/releases/tag/v7-beta-3)

**Comment by sanderlv** [comment]
Is that possible via HACS?

**Comment by johanfrick** [comment]
Yes, just enable beta in HACS for this card. There was a bug in beta-3, so use this one:
[v7-beta-4](https://github.com/johanfrick/custom-sonos-card/releases/tag/v7-beta-4)

**Comment by sanderlv** [comment]
Not sure how to do that...?
![Screenshot_20240204_184204_Home Assistant.jpg](https://github.com/johanfrick/custom-sonos-card/assets/16528916/1dc69f78-2886-4da9-b3d0-418bc5645c9c)

**Comment by johanfrick** [comment]
Click re-download

**Comment by sanderlv** [comment]
Done and step is 1 now. Will check and report back.

Thank you!!!

**Comment by sanderlv** [comment]
Today I update to 6.15.4 and now the steps are 2 again......

**Comment by punxaphil** [comment]
Yup, stick to the beta. I'll release it soon non beta

**Comment by punxaphil** [comment]
Fixed in https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.0.0
