### ISSUE TITLE
Overall volume relative instead of absolute

### ISSUE THREAD

**Issue by pjannink** [punxaphil/custom-sonos-card#294]
When I decrease Overall volume to f.i. 10% all my Sonos devices go to 10%. What I would like to have is an option to increase/decrease volume of all devices more relative.
So if I reduce overall volume from 50 to 40, it just decreases all my Sonos devices with 20%. The Sonos app also uses this relative increase and decrease, maintaining the balanced volume setting of all grouped devices.

**Comment by punxaphil** [comment]
Can you please try this beta? [v7-beta-7](https://github.com/punxaphil/custom-sonos-card/releases/tag/v7-beta-7)
```yaml
adjustVolumeRelativeToMainPlayer: true
```
---
PunxaPhil
[![image](https://github.com/johanfrick/custom-sonos-card/assets/26582898/9bebc1f6-6bda-4cbd-b596-50d3d2f712de)](https://www.buymeacoffee.com/punxaphil)

**Comment by pjannink** [comment]
Hi

 

Thank yo uso much fort he swift reply.

 

I loaded the beta but see no difference. 

Is anything needed with the sentence adjustVolumeRelativeToMainPlayer: true  ?

I searched in configuration.yaml but no entry on the Sonos-card

 

Please advise 😊 !

 

Thanks upfront

 

Paul

 

Van: Punxa Phil ***@***.***> 
Verzonden: donderdag 8 februari 2024 19:42
Aan: punxaphil/custom-sonos-card ***@***.***>
CC: pjannink ***@***.***>; Author ***@***.***>
Onderwerp: Re: [punxaphil/custom-sonos-card] Overall volume relative instead of absolute (Issue #294)

 

Can you please try this beta? v7-beta-7 <https://github.com/punxaphil/custom-sonos-card/releases/tag/v7-beta-7> 

adjustVolumeRelativeToMainPlayer: true
  _____  


PunxaPhil
image.png (view on web) <https://github.com/johanfrick/custom-sonos-card/assets/26582898/9bebc1f6-6bda-4cbd-b596-50d3d2f712de>

**Comment by pjannink** [comment]
Another finding:

 

If I mute one speaker, all shows as All are muted. Does not seem correct to me…

 



 

Van: Punxa Phil ***@***.***> 
Verzonden: donderdag 8 februari 2024 19:42
Aan: punxaphil/custom-sonos-card ***@***.***>
CC: pjannink ***@***.***>; Author ***@***.***>
Onderwerp: Re: [punxaphil/custom-sonos-card] Overall volume relative instead of absolute (Issue #294)

 

Can you please try this beta? v7-beta-7 <https://github.com/punxaphil/custom-sonos-card/releases/tag/v7-beta-7> 

adjustVolumeRelativeToMainPlayer: true
  _____  


PunxaPhil
image.png (view on web) <https://github.com/johanfrick/custom-sonos-card/assets/26582898/9bebc1f6-6bda-4cbd-b596-50d3d2f712de>

**Comment by punxaphil** [comment]
> Hi Thank yo uso much fort he swift reply. I loaded the beta but see no difference. Is anything needed with the sentence adjustVolumeRelativeToMainPlayer: true ? I searched in configuration.yaml but no entry on the Sonos-card 

Make sure you use v7-beta-7, then see the following video illustrating first without relative. Then how to enable relative, and how it works in the card.

https://github.com/punxaphil/custom-sonos-card/assets/26582898/45e6f0b3-e795-45e5-9f24-b3a011e5c3df

**Comment by pjannink** [comment]
Works like a charm! Was not aware the settings work via Edit.
May be consider a settings icon somewhere on the screen?
If possible I would add version to the general setting tab.

 

Thanks again, keep up the good work!

 

Van: Punxa Phil ***@***.***> 
Verzonden: vrijdag 9 februari 2024 13:36
Aan: punxaphil/custom-sonos-card ***@***.***>
CC: pjannink ***@***.***>; Author ***@***.***>
Onderwerp: Re: [punxaphil/custom-sonos-card] Overall volume relative instead of absolute (Issue #294)

 

Hi Thank yo uso much fort he swift reply. I loaded the beta but see no difference. Is anything needed with the sentence adjustVolumeRelativeToMainPlayer: true ? I searched in configuration.yaml but no entry on the Sonos-card

Make sure you use v7-beta-7, then see the following video illustrating first without relative. Then how to enable relative, and how it works in the card.

https://github.com/punxaphil/custom-sonos-card/assets/26582898/45e6f0b3-e795-45e5-9f24-b3a011e5c3df

**Comment by punxaphil** [comment]
> May be consider a settings icon somewhere on the screen?


I don't understand what you mean, please elaborate

**Comment by pjannink** [comment]
I understand.What I mean: you now have to set HA in Edit mode to reach all settings in the Sonos-Card. Would be great to have a shortcut to the settings directly from the card itself. No idea that is possible at all to be honestGreetings, PaulVerstuurd vanaf mijn iPadOp 9 feb 2024 om 15:20 heeft Punxa Phil ***@***.***> het volgende geschreven:﻿

May be consider a settings icon somewhere on the screen?

I don't understand what you mean, please elaborate

**Comment by punxaphil** [comment]
> I understand.What I mean: you now have to set HA in Edit mode to reach all settings in the Sonos-Card.

No you don't, you can still use yaml config. Edit mode is just a bonus

**Comment by punxaphil** [comment]
> Another finding: If I mute one speaker, all shows as All are muted. Does not seem correct to me… 

Thanks! I'll fix that

**Comment by punxaphil** [comment]
Good point, I've updated that now. Try it here: [v7.0.1](https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.0.1)

**Comment by pjannink** [comment]
Works like a charm! Thx again.PaulVerstuurd vanaf mijn iPadOp 17 feb 2024 om 15:08 heeft Punxa Phil ***@***.***> het volgende geschreven:﻿
Good point, I've updated that now. Try it here: v7.0.1

**Comment by punxaphil** [comment]
Yes, there is something strange there. I'll take a look

**Comment by punxaphil** [comment]
Can you play around with this beta and see if it behaves better? https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.2.0-beta

**Comment by pjannink** [comment]
Hi Punxa,

 

The main volume bar behaves much better but I still see some strange things:

Example:

 

OLD SETTING



 

When I reduce the main slider with 50% (so from 75% to appr 37% I would expect the other sliders to go to 50% and 25%. That is not the case: they jump to 62% and 12%



 

 

When you move the main slider all subsliders should change as follows:

 

Newvalue_subslider = oldvalue_subslider * (newvalue_mainslider/oldvalue_mainslider)

 

The newvalue_subslider should be tested not to be lower than 0 or higher than 100. 

 

When you move a subslider the mainslider should always be the average of all subsliders.

 

Some strange behavior can not be avoided I fear. If you change the OLD SETTING above by sliding the main slider to 100%, the Sonos with 50% changes to 75% what is correct. That means that the main slider results in 88% as average of 2 times 100 and 2 times 88. But that is only one correction so I could live with that.



 

One more thing: if I add two or more sonos in the group tab, I sometimes get an error message. In that case I have to add the boxes one by one. But on another occasion it works as designed and I can add more boxes in one action.

 

Keep up the great work!

 

Paul 

 

 

Van: Punxa Phil ***@***.***> 
Verzonden: maandag 4 maart 2024 07:38
Aan: punxaphil/custom-sonos-card ***@***.***>
CC: pjannink ***@***.***>; Author ***@***.***>
Onderwerp: Re: [punxaphil/custom-sonos-card] Overall volume relative instead of absolute (Issue #294)

 

Can you play around with this beta and see if it behaves better? https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.2.0-beta

**Comment by punxaphil** [comment]
Thanks for that detailed report. I hope I understood you correctly in this new beta release. Please try it out:  [v7.2.0-beta4](https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.2.0-beta4)

> One more thing: if I add two or more sonos in the group tab, I sometimes get an error message. In that case I have to add the boxes one by one. But on another occasion it works as designed and I can add more boxes in one action.

I've noticed such issues as well. I'm afraid that is out of my control.

**Comment by punxaphil** [comment]
Are you sure you are using beta4? It looks good when I try it. The below video with beta 4 follows the fractions correctly.

https://github.com/punxaphil/custom-sonos-card/assets/26582898/b54b807c-ef24-4caf-88bb-01afbb89a0f9

**Comment by pjannink** [comment]
Hi PunxaSeems you are right. I now loaded v4 on my iPad and there it works OK.One remark: when I adjust main volume, 3 of 4 sub volumes are set instantly. Only the last one has some delay (appr 1-2 seconds). Something you can fine-tune??Regards and thx for all the good work!PaulVerstuurd vanaf mijn iPadOp 5 mrt 2024 om 20:23 heeft Punxa Phil ***@***.***> het volgende geschreven:﻿
Are you sure you are using beta4? It looks good when I try it. The below video with beta 4 follows the fractions correctly.
https://github.com/punxaphil/custom-sonos-card/assets/26582898/b54b807c-ef24-4caf-88bb-01afbb89a0f9

**Comment by punxaphil** [comment]
Great it's working. I'll make a sharp release.
> delay 

I'm afraid not. I fire all volumes at the same time. Delays are only due to the Sonos Network, nothing I can affect.

---
PunxaPhil
[![image](https://github.com/johanfrick/custom-sonos-card/assets/26582898/9bebc1f6-6bda-4cbd-b596-50d3d2f712de)](https://www.buymeacoffee.com/punxaphil)

**Comment by punxaphil** [comment]
Released: https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.1.1

**Comment by pjannink** [comment]
Hi Punxa

 

Not sure what happened but suddenly the overall volume and some Sonos devices show 30% as their max volume:

 



Running HA 2024.3.1 and of course the latest version of your Sonos card.

 

Best regards, Paul

 

Van: Punxa Phil ***@***.***> 
Verzonden: dinsdag 5 maart 2024 21:10
Aan: punxaphil/custom-sonos-card ***@***.***>
CC: pjannink ***@***.***>; Author ***@***.***>
Onderwerp: Re: [punxaphil/custom-sonos-card] Overall volume relative instead of absolute (Issue #294)

 

Closed #294 <https://github.com/punxaphil/custom-sonos-card/issues/294>  as completed.

**Comment by punxaphil** [comment]
Check readme for dynamic volume

**Comment by pjannink** [comment]
Oeps, solved… Thx!

 

Van: Punxa Phil ***@***.***> 
Verzonden: vrijdag 15 maart 2024 11:33
Aan: punxaphil/custom-sonos-card ***@***.***>
CC: pjannink ***@***.***>; Author ***@***.***>
Onderwerp: Re: [punxaphil/custom-sonos-card] Overall volume relative instead of absolute (Issue #294)

 

Check readme for dynamic volume

**Comment by punxaphil** [comment]
👍
---
PunxaPhil
[![image](https://github.com/johanfrick/custom-sonos-card/assets/26582898/9bebc1f6-6bda-4cbd-b596-50d3d2f712de)](https://www.buymeacoffee.com/punxaphil)

**Comment by pjannink** [comment]
Hi

 

Another finding… Seems the Sonos card can not find the Sonos Serre in this picture. Though it works well.

But the screen shows 100% volume and strange NaN% as volume setting,

May be you can think of any solution?

Like make volume bar Serre grey instead of blue and calculate overall volume % excluding error-Sonos Serre??

 



 

Van: ***@***.*** ***@***.***> 
Verzonden: vrijdag 15 maart 2024 11:44
Aan: 'punxaphil/custom-sonos-card' ***@***.***>; 'punxaphil/custom-sonos-card' ***@***.***>
CC: 'Author' ***@***.***>
Onderwerp: RE: [punxaphil/custom-sonos-card] Overall volume relative instead of absolute (Issue #294)

 

Oeps, solved… Thx!

 

Van: Punxa Phil ***@***.*** ***@***.***> > 
Verzonden: vrijdag 15 maart 2024 11:33
Aan: punxaphil/custom-sonos-card ***@***.*** ***@***.***> >
CC: pjannink ***@***.*** ***@***.***> >; Author ***@***.*** ***@***.***> >
Onderwerp: Re: [punxaphil/custom-sonos-card] Overall volume relative instead of absolute (Issue #294)

 

Check readme for dynamic volume

**Comment by pjannink** [comment]
PS. Sonos Serre works fine, also on the Sonos App so no clue why your card does not see it anymore?

 

Van: ***@***.*** ***@***.***> 
Verzonden: dinsdag 19 maart 2024 10:26
Aan: 'punxaphil/custom-sonos-card' ***@***.***>; 'punxaphil/custom-sonos-card' ***@***.***>
CC: 'Author' ***@***.***>
Onderwerp: RE: [punxaphil/custom-sonos-card] Overall volume relative instead of absolute (Issue #294)

 

Hi

 

Another finding… Seems the Sonos card can not find the Sonos Serre in this picture. Though it works well.

But the screen shows 100% volume and strange NaN% as volume setting,

May be you can think of any solution?

Like make volume bar Serre grey instead of blue and calculate overall volume % excluding error-Sonos Serre??

 



 

Van: ***@***.*** ***@***.***>  ***@***.*** ***@***.***> > 
Verzonden: vrijdag 15 maart 2024 11:44
Aan: 'punxaphil/custom-sonos-card' ***@***.*** ***@***.***> >; 'punxaphil/custom-sonos-card' ***@***.*** ***@***.***> >
CC: 'Author' ***@***.*** ***@***.***> >
Onderwerp: RE: [punxaphil/custom-sonos-card] Overall volume relative instead of absolute (Issue #294)

 

Oeps, solved… Thx!

 

Van: Punxa Phil ***@***.*** ***@***.***> > 
Verzonden: vrijdag 15 maart 2024 11:33
Aan: punxaphil/custom-sonos-card ***@***.*** ***@***.***> >
CC: pjannink ***@***.*** ***@***.***> >; Author ***@***.*** ***@***.***> >
Onderwerp: Re: [punxaphil/custom-sonos-card] Overall volume relative instead of absolute (Issue #294)

 

Check readme for dynamic volume

**Comment by pjannink** [comment]
Update,

 

I had to restart Sonos Serre as also in the Sonos 2 app it behaved strange. 

Still would be nice to have proper error handling like described below…

 

Nice to see that your volume percentages are now identical to those in the sonos app 😊 (group volume and volume for each device).

 

Regards, Paul

 

Van: ***@***.*** ***@***.***> 
Verzonden: dinsdag 19 maart 2024 10:29
Aan: ': 'punxaphil/custom-sonos-card'' ***@***.***>; 'punxaphil/custom-sonos-card' ***@***.***>
Onderwerp: FW: [punxaphil/custom-sonos-card] Overall volume relative instead of absolute (Issue #294)

 

PS. Sonos Serre works fine, also on the Sonos App so no clue why your card does not see it anymore?

 

Van: ***@***.*** ***@***.***>  ***@***.*** ***@***.***> > 
Verzonden: dinsdag 19 maart 2024 10:26
Aan: 'punxaphil/custom-sonos-card' ***@***.*** ***@***.***> >; 'punxaphil/custom-sonos-card' ***@***.*** ***@***.***> >
CC: 'Author' ***@***.*** ***@***.***> >
Onderwerp: RE: [punxaphil/custom-sonos-card] Overall volume relative instead of absolute (Issue #294)

 

Hi

 

Another finding… Seems the Sonos card can not find the Sonos Serre in this picture. Though it works well.

But the screen shows 100% volume and strange NaN% as volume setting,

May be you can think of any solution?

Like make volume bar Serre grey instead of blue and calculate overall volume % excluding error-Sonos Serre??

 



 

Van: ***@***.*** ***@***.***>  ***@***.*** ***@***.***> > 
Verzonden: vrijdag 15 maart 2024 11:44
Aan: 'punxaphil/custom-sonos-card' ***@***.*** ***@***.***> >; 'punxaphil/custom-sonos-card' ***@***.*** ***@***.***> >
CC: 'Author' ***@***.*** ***@***.***> >
Onderwerp: RE: [punxaphil/custom-sonos-card] Overall volume relative instead of absolute (Issue #294)

 

Oeps, solved… Thx!

 

Van: Punxa Phil ***@***.*** ***@***.***> > 
Verzonden: vrijdag 15 maart 2024 11:33
Aan: punxaphil/custom-sonos-card ***@***.*** ***@***.***> >
CC: pjannink ***@***.*** ***@***.***> >; Author ***@***.*** ***@***.***> >
Onderwerp: Re: [punxaphil/custom-sonos-card] Overall volume relative instead of absolute (Issue #294)

 

Check readme for dynamic volume

**Comment by punxaphil** [comment]
Could your stop posting through mail? Conversations becomes very bloated.
Would appreciate if you clean it up
