### ISSUE TITLE
Feature Request - add custom button to sections footer

### ISSUE THREAD

**Issue by KNicholson-VII** [punxaphil/custom-sonos-card#295]
Feature Request
Add an option to link to a URL in the sections footer. And/or other HA buttons such as call service.  

My usecase is a back button for a wall panel.

Thank you!

**Describe alternatives you've considered**
I am not knowledgeable enough to create something custom myself.

**Comment by punxaphil** [comment]
So you want to link to for instance the volumes section?

**Comment by KNicholson-VII** [comment]
My idea was a button that could link outside the card itself. For example, I have created a Lovelace subview with the panel layout (single card). Having a back button or a 'navigate' button in the footers section would be useful.

thanks

**Comment by punxaphil** [comment]
This card is not aimed at replacing HA dashboard features. I recommend you to use horisontal/vertical stack card (or some other layout card) and add a button.
