### ISSUE TITLE
UPnP Error 501 when connecting several speakers since lates v7.0.0

### ISSUE THREAD

**Issue by neo171190** [punxaphil/custom-sonos-card#296]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue: 7.0.0

**Last working release (if known): 6.15.4

**Browser and Operating System:**
Safari, Chrome, iOS Home Assistant App (iPhone and iPad)

**Description of problem:**
Everthing working fine, instead of connecting several Sonos-Speakers. E.g. playing music from Spotify at Sonos Speaker kitchen ist working. But when you try to connect kitchen with living room there is a UPnP 501 error:
(error in german so i try to translate) "Error on calling media_player/join. Error on calling SonosSpeaker.join on [SpeakerName]. UpnP Error received. Action failed from [Speaker IP Address]" 
Sonos is connected to HA via fritz.box.
Restarting of Raspberry Pi 4 running HA, Sonos speaker and clearing browser cache on alle devices didn't work.

**Comment by punxaphil** [comment]
I'm afraid this is something you need to bring up with the maintainers of the Sonos integration
