### ISSUE TITLE
All Favorites icons not showing on Android HA app

### ISSUE THREAD

**Issue by mrosseel** [punxaphil/custom-sonos-card#297]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

v7.0.1

**Last working release (if known):**

A few weeks ago, as soon as the favorites switched to icons

**Browser and Operating System:**

Not working on android HA app, Android 13/14

**Description of problem:**

The 'All Favorites' view only shows a few icons in the android Home Assistant App, but all can be seen in the browser.
I would expect all icons to be visible in the android app.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

No icons on android app:
![signal-2024-02-19-160842](https://github.com/punxaphil/custom-sonos-card/assets/1465310/d7b76a35-9f6e-4703-983d-12d16f7613ef)

Icons in web browser:
![Screenshot 2024-02-19 at 16 14 31](https://github.com/punxaphil/custom-sonos-card/assets/1465310/3b4f9bc4-4cf4-46ed-b3aa-49b9862b11bb)

**Comment by punxaphil** [comment]
Some issue with http I am guessing. Try `replaceHttpWithHttpsForThumbnails: true`. Or change from internal to external home assistant URL in the app
