### ISSUE TITLE
Ignore Volume Level Not Working

### ISSUE THREAD

**Issue by rmbeatty** [punxaphil/custom-sonos-card#301]
Hi,
Really appreciate you adding features for both of my issues.  Sorry for the delay in testing them.  The Ignore Volume for an Entity is a great idea to solve the issue I had (Sonos box has fixed volume, volume is controlled by a stereo receiver) however it doesn't appear to be working.  There are three issues:
1) Using the All Volume Slider or the Volume Slider for the entity throws an error.  "Failed to call service media player volume set"  The error references only the Sonos box that has the fixed volume.
2) If the Sonos box with the fixed volume is the master controller in the group, the All Volume slider does not adjust the volume of the other sliders, even though I have the fixed one listed in the new  Ignore Volume box
3) If the Sonos box with the fixed volume is NOT the master controller in the group, it works correctly.

So overall, not sure the Ignore Volume is working at all as I think #2 and #3 were the behavior that existed before I upgraded to 7.0

**Comment by punxaphil** [comment]
You are right, this needs some more tweaking. What is currently working is showing volume correctly in the player section. I'll look into improving this.

**Comment by punxaphil** [comment]
Can you have a look at this beta version and see if behaves correctly? https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.2.0-beta

**Comment by punxaphil** [comment]
Released: https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.1.1

**Comment by rmbeatty** [comment]
Thanks.  Works fine
