### ISSUE TITLE
HEOS compatibility

### ISSUE THREAD

**Issue by Webbeh** [punxaphil/custom-sonos-card#308]
**Is your feature request related to a problem? Please describe.**
This feature request is not linked to a problem.

**Describe the solution you'd like**
This custom card looks fantastic and it should honestly be included by default in Home-Assistant.

It is however not compatible with anything but Sonos speakers, even if other brands support the same featureset. This is the case of Denon HEOS devices, for example.

I would like to be able to use the HEOS speakers together with the SONOS speakers on your custom card. I am aware that the speaker grouping will not work across brands, but if this custom card was used solely with HEOS speakers (just as it is for SONOS speakers), it should work.

**Describe alternatives you've considered**
At the moment, the alternative is to not use your custom card.

**Additional context**
Right at this moment, this custom card does simply not recognize any of my speakers as compatible (which is most certainly by design).

Thank you very much !

**Comment by punxaphil** [comment]
There is a config to show all players
![image](https://github.com/punxaphil/custom-sonos-card/assets/26582898/6992d9a9-df6a-4b41-b381-e81e6515a46f)

**Comment by Webbeh** [comment]
...wow, how did I miss that?.....

Sorry for my idiocy. Thank you!
