### ISSUE TITLE
Grouping - ungroup actual player while group another does not work as expected

### ISSUE THREAD

**Issue by ecser99** [punxaphil/custom-sonos-card#309]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
HA Core: 2024.1.2
Sonos Card: V7.1.0

**Last working release (if known):**

**Browser and Operating System:**

Win11 / Chrome  ver: 122.0.6261.95 , Android / Fully Kiosk Browser

**Description of problem:**

Use case:
I use the Sonos card on an Android phone as a dedicated room controller for Player 1 . I have set entityId: Player 1 
I go to another room, so I want to "move" the music from the current Player 1 to the Player 2, so that Plaer 2 starts playing and Player 1 stops palying.

Steps to reproduce:
Music is playing on Player 1, no music on Player 2. The Sonos Card shows group: Player 1 in the top row.
1. open setction "grouping"
2. select Player 2 in the list (Player 1 and 2 are selected)
3. deselect Player 1
4. hit Apply. 
5. Result: Player 1 continues playing, Player 2 does not play. The "player" section shows up, the selected player is Player 2.

Expected behaviour:
5. Expected result: Player 2 starts playing, Player 1 stops playing. 
The player section shows up and - when this is a dedicated card with entityId: Player 1 - the selected player must be Player 1. When this is not a dedicated card, then the new active group  (Player 2) should be active here.

Remark 1: "Moving" the music like described above is a normal function of the original Sonos S1 and S2 app, this should work in the same way on the Sonos Card. 
Remark 2: in the grouping section beside the "Apply" button there is a "Cancel" button, but I don't see any function of it.

Thanx!

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by punxaphil** [comment]
That's a scenario I've never considered. Thanks for sharing.
I'll take a look

**Comment by punxaphil** [comment]
Please try it with this beta and let me know if it works [v7.2.0-beta2](https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.2.0-beta2)

**Comment by ecser99** [comment]
Grouping and ungrouping in one step works as expected, thank you!
This is still open:
In the grouping section beside the "Apply" button there is a "Cancel" button, but I don't see any function of it.
Maybe "Cancel" should reverse the last selections made. Now it doesn't seem to do anything.
