### ISSUE TITLE
Dynamically adjusting card height

### ISSUE THREAD

**Issue by Caligo82** [punxaphil/custom-sonos-card#313]
I really love the dynamically adjusting volume slider (as well as mostly all of the layout actually).
The thing that for me makes it a bit tricky to integrate in a pre existing dashboard is the fact that I can only set a fixed height.
So I reduced the height to something like 20% to only see one volume slider of one entity. But opening the settings it pulls up a scrolling block on the right (and subsequently lower) edge of the card.

![issue](https://github.com/punxaphil/custom-sonos-card/assets/31889595/0d3667c4-8086-4ef4-9020-78696fb32427)

A similar issue exists with the group/player selection window with several sections. If there are too many players you'll always have a scrolling bar, unless you adjust it and end up with a certain additional amount of unused space in the card.

As a solution I'd like it to be a dynamically adjusting card height.

I looked through closed issues, but it seems that issue wasn't really mentioned yet. I think the benefit would really be more flexibility in integrating it. Thanks in advance for checking.

**Comment by punxaphil** [comment]
Did you try `heightPercentage: auto`?
(I realise now that it's an undocumented feature)

**Comment by Caligo82** [comment]
Hey that's actually great. Maybe update the documentation if possible. 😄 
One nitpicking thing still. I feel like it's maybe cut a bit too close on the lower edge. Fonts get a bit close to the card finishing line:
![edges](https://github.com/punxaphil/custom-sonos-card/assets/31889595/b033336e-7961-41ff-b6d3-f3f99c184f96)
Other than that: thank you very much!
