### ISSUE TITLE
Autoheight, artwork and padding

### ISSUE THREAD

**Issue by Caligo82** [punxaphil/custom-sonos-card#315]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

7.1.2 (probably earlier)

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

When setting height of the card to auto it cuts the Artwork in the player window:

![artwork cut](https://github.com/punxaphil/custom-sonos-card/assets/31889595/379e9061-6f2b-4c42-87a0-54127313d679)

Here's the yaml behind these two cards:

First:

type: custom:sonos-card
heightPercentage: auto
dynamicVolumeSlider: true

Second:

type: custom:sonos-card
heightPercentage: null
dynamicVolumeSlider: true

Second Issue I noticed is with the dynamic volume slider. When I completely remove the player title the card padding on the upper section is too short:

![padding without title](https://github.com/punxaphil/custom-sonos-card/assets/31889595/27bf32b4-0a43-435f-8989-f019808dc279)

Maybe it would also be possible to hide the settings button next to the volume slider to get more screen estate for the slider?

thanks for checking!

**Comment by punxaphil** [comment]
Thanks for reporting. Fixed: https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.1.4

**Comment by Caligo82** [comment]
Well awesome. Thank you very much!

**Comment by punxaphil** [comment]
You're welcome!

---
PunxaPhil
[![image](https://github.com/johanfrick/custom-sonos-card/assets/26582898/9bebc1f6-6bda-4cbd-b596-50d3d2f712de)](https://www.buymeacoffee.com/punxaphil)

**Comment by Caligo82** [comment]
I noticed a little layout bug when using the slider. Introduced by the increased padding... or rather made visible by it:

![edges](https://github.com/punxaphil/custom-sonos-card/assets/31889595/7a3ee046-f3e9-44a0-bf93-d0ad304632b8)

**Comment by Caligo82** [comment]
I noticed a little layout bug when using the slider. Introduced by the increased padding... or rather made visible by it:

![layout bug](https://github.com/punxaphil/custom-sonos-card/assets/31889595/f6dbf348-5639-4ff2-9d73-2c422e178c5b)

**Comment by punxaphil** [comment]
Thanks! Fixed in https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.3.0
