### ISSUE TITLE
Customizable dynamic volume values

### ISSUE THREAD

**Issue by Caligo82** [punxaphil/custom-sonos-card#316]
**Is your feature request related to a problem? Please describe.**

No problem really

**Describe the solution you'd like**

I wonder if it would be possible to make the dynamic volume levels customizable.
There are two values. One is the "switch" value (now 20%) and the other is the "limit" value (now 30%).
The limit value could also be relative to the switch value instead of an absolute value. Comes to the same but maybe there's a benefit I can't see yet.

**Describe alternatives you've considered**

Maybe I could limit the max value of the Sonos player itself to achieve a similar result. But it sort of works against the idea of a dynamic volume slider.

**Additional context**
Sorry for yet another github issue. 😊

**Comment by punxaphil** [comment]
Thanks for this request! Added it here: https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.3.0
use `dynamicVolumeSliderThreshold` and `dynamicVolumeSliderMax`

**Comment by Caligo82** [comment]
I'm not sure if I'm doing it wrong:

  - type: custom:sonos-card
    heightPercentage: auto
    dynamicVolumeSlider: true
    entities:
      - media_player.sonos_wohnzimmer
    sections:
      - volumes
    entityNameRegexToReplace: Sonos ARC
    showVolumeUpAndDownButtons: true
    hideVolumeCogwheel: true
    dynamicVolumeSliderThreshold: 30
    dynamicVolumeSliderMax: 40
    card_mod:
      style: |
        ha-card {
          color: white !important;
          background: transparent;
          --accent-color: pink;
          --primary-color: white;
          --secondary-text-color: white;
          --secondary-background-color: pink;
        }  

Doesn't change it this way...

**Comment by punxaphil** [comment]
That looks messed up. Please use a code block

**Comment by Caligo82** [comment]
Adjusted, sorry about the layout 🤣

**Comment by punxaphil** [comment]
That looks correct, please double check which version you use. Try and clear browser cache or use private session.

**Comment by Caligo82** [comment]
I checked again, I don't think it's in the code:

https://github.com/punxaphil/custom-sonos-card/compare/v7.3.0-beta2...v7.3.0

I redownloaded it and looked for "dynamicVolumeSliderThreshold" in the custom-sonos-card.js - to no avail...

**Comment by punxaphil** [comment]
Sorry, somehow I missed that commit in the tag... new release created: https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.4.0
