### ISSUE TITLE
Relative Volume

### ISSUE THREAD

**Issue by rmbeatty** [punxaphil/custom-sonos-card#320]
If I have the volume in individual rooms set differently, say Living Room is 38% and bedroom is 15%, when using the All Volume Slider if I move it to say 30%, it moves all volume sliders to 30%.  So in my example it lowers the Living Room but raises the Bedroom.  is it possible to give an option so the volume slider is relative to the existing positions of the other sliders?  So, in my example the Living Room would go to 30% and the Bedroom would go to 7%.  Is this a feature that could be added?

**Comment by punxaphil** [comment]
Next time, please consider searching.
https://github.com/punxaphil/custom-sonos-card/issues/294#issuecomment-1934726037
