### ISSUE TITLE
Preferred volume control in Main-tab

### ISSUE THREAD

**Issue by gaga191281** [punxaphil/custom-sonos-card#326]
It would be very beneficial to be able to link the main volume slider (the one at the home view) to a specific player.
Use case: I have a Sonos speaker and a tablet that uses the SONOS-CARD as control unit. So in general every tablet is used to control the volume of the player of its room.
When players are combined in a group and a user wants to turn up or down the volume it is not convenient to first go to the volume tab, find the player and change the volume. It also accidentially happens that a user changes the volume of the whole group instead the volume just for the wanted speaker.
Would be nice to set a preferred volume control to the main control tab. (Just like its possible to set a preferred player entity)

**Comment by punxaphil** [comment]
Try it in the following release. Use `playerVolumeOnlyAffectsMainPlayer: true`

[v7.7.0](https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.7.0)

🚀 Features
[feature: make it possible to only control main player volume in player section](https://github.com/punxaphil/custom-sonos-card/commit/af2cb13cf20f2b2944ece9d428bd0730a742855b)
🐛 Fixes
[fix: missing name for players that don't support grouping](https://github.com/punxaphil/custom-sonos-card/commit/de8a89807b652a904a13fcfd914d936dd91e9030)
[fix: log warning if player is not available](https://github.com/punxaphil/custom-sonos-card/commit/9f452381c8aa39cfbd2b44c52567c2692a11a1fa)

**Comment by gaga191281** [comment]
Hi Phil.. you are a beast for reacting and implementing this so quickly. Thanks a lot.
Short question. Is there a way to install and test it without waiting for the release to be published?

**Comment by punxaphil** [comment]
Sorry about that, I forgot to activate the release. It should be available now!

**Comment by gaga191281** [comment]
Hi Phil. Tried to use this new feature. Updated to the latest version 7.7.0 and added the property in the yaml, since there was no option in the visual part of the card.

The yaml looks like this:

`  - type: custom:mushroom-title-card
    title: Musik
  - type: custom:sonos-card
    sections:
      - player
      - volumes
      - groups
      - grouping
      - media browser
    entityId: media_player.laras_zimmer
    topFavorites:
      - ''
    dynamicVolumeSlider: true
    artworkAsBackground: true
    playerVolumeOnlyAffectsMainPlayer: true`

Whe grouping some players and changing the volume from the main-tab (the one with the house). It still changes the volume of all players. What did I do wrong?

**Comment by punxaphil** [comment]
Please try this one: https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.7.1

**Comment by gaga191281** [comment]
Did the update, grouped some players, but still the volume of all players are changed.
Any suggestions?

**Comment by punxaphil** [comment]
I tried it now with https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.8.0

https://github.com/punxaphil/custom-sonos-card/assets/26582898/5426815f-e8ca-48d8-bdb5-26d9a8188eab

**Comment by punxaphil** [comment]
I don't get it

**Comment by gaga191281** [comment]
Okay, here is the use-case scenario:

There are multiple rooms (9 in my case) with each a SONOS speaker an a wall-mounted tablet in it. Every talbet has the homeassistant dashboard running with its own page and sonos-card instance. This sonos-card is set to the specific entityID (entityId: media_player.livingroom for instance)

Let's assume music is playing in the living room. One of the children now wants to here the same music in its room and creates a group where the living room is the coordinator (main player).
Now when this child wants to turn up the volume in its room. And therefore uses the slider on the main page of the sonos-card.

Behavoiur with `playerVolumeOnlyAffectsMainPlayer: false` all players in that group are getting louder. (not wanted)
Behavoiur with `playerVolumeOnlyAffectsMainPlayer: true` only the main-player which would be the living-room in this scenario is getting louder. (not wanted)
Wanted behaviour: the player in the childrens room which is set in `entityID` is getting louder, living room stays the same.

I hope this makes is a little clearer.

**Comment by punxaphil** [comment]
Yeah, I get it now, I think. Will think about a solution.

**Comment by punxaphil** [comment]
Try https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.9.0
`playerVolumeEntityId: media_player.bedroom # default is empty. Use this to control the volume of another player in the player section. Entity ID must the selected player or part of the selected player's group, otherwise it will not be controlled.`

**Comment by gaga191281** [comment]
Hi Phil. Tried the new version (Updated to 7.10 and cleaned the cache). 
According to your implementation changes the `playerVolumeOnlyAffectsMainPlayer` should be gone. But it is still available and functional. The new property does not work for me. Do I miss anything in the update process?

**Comment by gaga191281** [comment]
After my update the version strangely stayed with 7.8 and HomeAssistant didn't offer me any further updates. Therefore I redownloaded the integration.
It now works like a charm.
Thank you very much for you work.
