### ISSUE TITLE
Dedicated room controller  - player section and  main volume controll only for the player of the room.

### ISSUE THREAD

**Issue by ecser99** [punxaphil/custom-sonos-card#327]
Thank you for this card, it is really great!

**Is your feature request related to a problem? Please describe.**
Use case:
I use the Sonos card on an Android phone (and another on a tablet) as  dedicated room controllers for the room players. The main purpose is to controll basic functions inuitively (play / pause, volume, group / ungroup etc.) for the room where the controller is placed.

Problem 1: 
When I change volume on the #player section, and other players are grouped, the volume level of the other players change as well.  This is not good as I basically can't hear the other players and do not want to change those volumes. I would expect to only change the volume for the  player 1 of this room. 

Problem 2:
When I group the player 1 to player 2 and I ungroup player 1, then the sonos card #player section changes to player 2. This is logical, when you want to controll player 2 with this controller, but a dedicated controller should show  the player 1 on the #player section.

**Describe the solution you'd like**
A dedicated controller should shows allways the room it is attached to and controll primarily the volume of that room, just like a physical controller switch on the wall. It should be used intuitively. 

Solution 1: 
a configuration option to restrict the main volume controller on the #player" section to the dedicated player.  The dedicated player should be the one already configured in "entityId:"
Controlling other player's volume should be still possible for the user on the sections:  #groups and #volumes.

Solution 2.
a configuration option to rectrict the #player section to the dedicated player configured in "entityId:".  The user should be able to select another player to controll, but the sonos card itself should not change the player (like described above), the dedicated player should allways shown (alone or as a part of a group) on the #player section.

**Describe alternatives you've considered**
With "Fully remote browser" and its HA integration it is possible to make automations and send the page to the start URL whenever another player is shown, but it is not ideal.

**Additional context**
This should make the card a great room controller, a solution, which  is missing in the original sonos app as well.

**Comment by punxaphil** [comment]
https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.8.0
`dontSwitchPlayerWhenGrouping: true # default is false. Will not switch to another player if main player is ungrouped.`
