### ISSUE TITLE
Allow option for complete favorites list without scrolling

### ISSUE THREAD

**Issue by robchandhok** [punxaphil/custom-sonos-card#337]
**Is your feature request related to a problem? Please describe.**
I've finally added enough Sonos favorites (My Sonos) that the Favorites pane has started to have scroll bars.  

**Describe the solution you'd like**
I think some setting (perhaps 'auto' was meant to do this, but it doesn't, perhaps 'show-all') 

**Describe alternatives you've considered**
A workaround for my current list of favorites is to set `heightPercentage: 120`.  I think I would have to keep changing it.  I can see how the list view (1 column) is fine to scroll, but not with the icons (I'm using 4 across).

**Additional context**
I am showing Favorites only in their own card, in a masonry page with the player in a different card.

Thank you for the great card!

**Comment by punxaphil** [comment]
Others have reported success with `heightPercentage: auto`.
That doesn’t work for you?

**Comment by robchandhok** [comment]
Doh.  I mistakenly thought that omitting `heightPercentage` was the equivalent of `auto`, but it is `100` now that I read more carefully.  Totally my mistake, sorry!

I might default to `auto` instead of 100, but that's just me.
