### ISSUE TITLE
mediaBrowserHideTitleForThumbnailIcons: true not working 

### ISSUE THREAD

**Issue by stingone** [punxaphil/custom-sonos-card#351]
As soon i add the line below, the mediabrowser is not longer showing. I use 3 rows 
mediaBrowserHideTitleForThumbnailIcons: true

**Comment by punxaphil** [comment]
Thanks for reporting. I'll take a look

**Comment by punxaphil** [comment]
Please share screenshots. With and without the setting

**Comment by punxaphil** [comment]
I cannot reproduce the bug. The setting works when I try it. Please provide more info.
<img width="485" alt="image" src="https://github.com/punxaphil/custom-sonos-card/assets/26582898/63da02a9-7008-4ffb-b250-7f1df617f96c">
