### ISSUE TITLE
Viewing current playlist/queue

### ISSUE THREAD

**Issue by swimminshell** [punxaphil/custom-sonos-card#355]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm unable to see the full playlist while listening to music. For example, when I'm in a playlist on Deezer, I can see the current song title, artist, and album cover, but I cannot see the upcoming songs. If I want to navigate through my playlist, I have to do it blindly.

**Describe the solution you'd like**
I would like to have the ability to view the full playlist, including previous and upcoming songs, in either the main view or in a new tab. Additionally, it would be helpful to have a special icon indicating the currently playing song.

**Describe alternatives you've considered**
One alternative solution could be to implement a feature where users can navigate through the playlist using voice commands or gestures.

Thank you for this great card

**Comment by punxaphil** [comment]
Yea, I'm missing that too. Unfortunately home assistant doesn't support it.
Before it can happen the maintainers of https://www.home-assistant.io/integrations/sonos/ must implement support for what you are asking (and maybe they can't either, if Sonos api doesn't support it).

**Comment by swimminshell** [comment]
thank you @punxaphil

**Comment by punxaphil** [comment]
They added support now in the Sonos integration, and because of that we can now show the playlist. It is still in beta state for this card. Please try it out and come with feedback:
https://github.com/punxaphil/custom-sonos-card/releases/tag/v8.0.0-beta1

**Comment by punxaphil** [comment]
@swimminshell ☝️

**Comment by Vansmak** [comment]
I've been doing this with a node red work around so good to see this. But how do I implement this? I have the beta.

**Comment by punxaphil** [comment]
Make sure you have queue under sections.
```
type: custom:sonos-card
sections:
  - queue
  - ...

```

**Comment by punxaphil** [comment]
[v8.0.0](https://github.com/punxaphil/custom-sonos-card/releases/tag/v8.0.0) released!
<img width="1221" alt="image" src="https://github.com/user-attachments/assets/89ae6274-6e47-4cb9-81dd-ad01924ae9e5">

---
PunxaPhil
[![image](https://github.com/user-attachments/assets/cb2e240e-f9ca-4900-a425-b8089216c1ee)](https://patreon.com/PunxaPhil) [![image](https://github.com/johanfrick/custom-sonos-card/assets/26582898/9bebc1f6-6bda-4cbd-b596-50d3d2f712de)](https://www.buymeacoffee.com/punxaphil)
