### ISSUE TITLE
behavior of the backward button 

### ISSUE THREAD

**Issue by swimminshell** [punxaphil/custom-sonos-card#356]
**Is your feature request related to a problem? Please describe.**
I find it unusual that the behavior of the back button is different from what I'm accustomed to in most media players. Typically, when a media is playing and I press the back button, it resets the media to the beginning. However, in the current setup, pressing the back button takes me directly to the previous media, which is not the expected behavior.

**Describe the solution you'd like**
I would like the behavior of the back button to be consistent with most media players, where pressing it while a media is playing resets the media to the beginning. This would align with users' expectations and provide a more intuitive experience.

**Describe alternatives you've considered**
One alternative solution could be to provide users with the option to customize the behavior of the back button through settings, allowing them to choose between going to the previous media or resetting the current media to the beginning.

Thank You

**Comment by punxaphil** [comment]
I'm not implementing any back functionality. I'm just using what home assistant provides. You need to make a request to the home assistant team.
