### ISSUE TITLE
Req: Show playlist of player

### ISSUE THREAD

**Issue by Vinisz** [punxaphil/custom-sonos-card#357]
**Is your feature request related to a problem? Please describe.**
No, all good, just requesting new feature

**Describe the solution you'd like**
I would like to have a view which shows current playlist of the player

**Describe alternatives you've considered**
Nothing really, seems just to be not there

**Additional context**
I hope the request is clear like this

**Comment by punxaphil** [comment]
https://github.com/punxaphil/custom-sonos-card/issues/355#issuecomment-2060591607

**Comment by punxaphil** [comment]
@Vinisz 
They added support now in the Sonos integration, and because of that we can now show the playlist. It is still in beta state for this card. Please try it out and come with feedback:
https://github.com/punxaphil/custom-sonos-card/releases/tag/v8.0.0-beta1

Preferably comment here: #355
