### ISSUE TITLE
Req: Open a "favorite" instead of instant play

### ISSUE THREAD

**Issue by Vinisz** [punxaphil/custom-sonos-card#358]
**Is your feature request related to a problem? Please describe.**
No, all good

**Describe the solution you'd like**
When I click a "playlist" in "All favorites" , I would like the playlist to open to I can select a track of that playlist instead of current behavior (playlist just starts playing when clicked)

Optional : Add a "play" button after opening the playlist so you can still choose to play entire playlist instead of track from the playlist

**Describe alternatives you've considered**
For selecting a single track from Spotify for example, I now have to go all the way through the "media browser"

**Additional context**
None

**Comment by punxaphil** [comment]
https://github.com/punxaphil/custom-sonos-card/issues/228#issuecomment-1841627407
