### ISSUE TITLE
Wrong radio station playing

### ISSUE THREAD

**Issue by MNLFDF** [punxaphil/custom-sonos-card#360]
V7.20 Still “Apply” button and none responding “scripts” #314  

This isn’t solved yet. Sonos is still going crazy and Sonos Card is not responding as intended. So please open the original bug report again. I hope you can solve this. Otherwise version 7.0.1 is the latest version I 
can use.

and I can indeed hide the “apply” button with “skipApplyButtonWhenGrouping: true”

**Comment by MNLFDF** [comment]
I updated to the latest version available
[X ] I cleared the cache of my browser
Release with the issue:
HA 2024.4.0 / Sonos Card v7.10.0

Last working release (if known):
HA 2024.4.0 / Sonos Card v7.01

Browser and Operating System:
Home Assistant app for iPad (v17.4) and iPhone (v17.4)

Description of problem:
Installed Sonos Card  7.10.0

Then tried to select the second option in my list “JOE NL”. (See picture first post ). Then the Sonos card get me “JOE Easy” the first one on the list. I can’t select any other options, because the card doesn’t seems to react on that selection. I can still pause the stream and turn up the volume tho. And when I go to the favorites page, I can switch to another radio station. 

After pressing “Joe NL”, the original Sonos app goes wild. Group and ungroup speakers on and on. I need to restart Home Assistant to stop this behavior.

The code I use for the dashboard:

/type: custom:sonos-card
sections:
  - player
  - volumes
  - groups
  - grouping
  - media browser
predefinedGroups:
  - name: Joe Easy
    media: Joe Easy
    entities:
      - player: media_player.tv
        volume: 3
      - player: media_player.homecinema
        volume: 3
      - player: media_player.erker
        volume: 4
      - player: media_player.tafel
        volume: 3
      - player: media_player.keuken
        volume: 10
  - name: Joe NL
    media: JOE Nederland
    entities:
      - player: media_player.tv
        volume: 3
      - player: media_player.homecinema
        volume: 3
      - player: media_player.erker
        volume: 4
      - player: media_player.tafel
        volume: 3
      - player: media_player.keuken
        volume: 10
  - name: NPO Soul & Jazz
    media: NPO Soul & Jazz
    entities:
      - player: media_player.tv
        volume: 3
      - player: media_player.homecinema
        volume: 3
      - player: media_player.erker
        volume: 4
      - player: media_player.tafel
        volume: 3
      - player: media_player.keuken
        volume: 10
  - name: Radio 10
    media: Radio 10
    entities:
      - player: media_player.tv
        volume: 3
      - player: media_player.homecinema
        volume: 3
      - player: media_player.erker
        volume: 4
      - player: media_player.tafel
        volume: 3
      - player: media_player.keuken
        volume: 10
mediaArtworkOverrides:
  - ifMissing: false
    imageUrl: /local/images/sonoscard/tv1.gif
    mediaTitleEquals: TV
dynamicVolumeSlider: true
showVolumeUpAndDownButtons: true
mediaBrowserItemsPerRow: 5
card_mod:
  style:
    .: ''
    sonos-player$ sonos-player-controls$ sonos-volume$: |
      ha-control-slider {
        height: 20px;
      }
      ha-icon-button {
        --mdc-icon-button-size: 3rem !important;
        --mdc-icon-size: 2rem !important;
      }
    sonos-groups$: |
      mwc-list {
        width: 10rem;
      }

**Comment by punxaphil** [comment]
I rephrased the title, let me know if you disagree.
Also, please try with the latest version.

**Comment by MNLFDF** [comment]
It’s not only playing the wrong radio station, also my Sonos System gets crazy. If I open the original Sonos app I see the speakers group, ungroup, group with another, ungroup, group with a single speaker, ungroup and so on. This only stops when I reboot Home Assistant.

I installed v7.10.0 (the latest) this morning, because I still have faith it will work some day, but the result is again a Sonos system getting crazy and playing the wrong radio station. Like all versions between 7.0.1 and the latest do. 

Version 7.0.1 has a fast response and works as intended.

**Comment by punxaphil** [comment]
I have been trying to reproduce this, but can't. It all works fine when I try to follow your scenario. You still seeing this error?

**Comment by MNLFDF** [comment]
Tried to update to the 7.14 version last week, and still got this behavior. Everything is working smoothly when I installed 7.01 again. So I will stick to this version. Don’t know what’s happening, but get all kind of errors when using another version and Home Assistant feels slow (and struggling in the background somehow) when using any version above 7.01
