### ISSUE TITLE
Dedicated room controller - dontSwitchPlayerWhenGrouping does not allways work

### ISSUE THREAD

**Issue by ecser99** [punxaphil/custom-sonos-card#368]
**Checklist:**

- [x ] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**
Core 2024.5.0
sonos card: v7.10.0

**Last working release (if known):**

**Browser and Operating System:**
win11, chrome
android, Fully Kiosk Browser

**Description of problem:**

I use two different sonos players with two dedicated tablets with  custom sonos card. dontSwitchPlayerWhenGrouping is set on both tablets.

Steps (OK):
On tablet 1 I start playing a song on sonos 1
On tablet 1 I add the sonos 2 (both players are playing)
On tablet 1 I deselect sonos 1 (sonos 1 stops playing, sonos 2 continues playing)
On tablet 1 the player screen stays on sonos 1 (OK, works as expected)

Steps (NOT OK):
On tablet 2 I start playing a song on sonos 2
On tablet 2 I add the sonos 1 (both players are playing)
On tablet 1 I deselect sonos 1 (sonos 1 stops playing, sonos 2 continues playing)
On tablet 1 the player screen changes to sonos 2 **(NOT OK, the player should stay on sonos 1)**

**Additional information:**
The reason for the different results may be that the master player is different in the two scenarios.

**Comment by punxaphil** [comment]
You can use 
```yaml
entityId: media_player.sonos_bedroom # Forces this player to be the selected one on loading the card (overrides url param etc)
```

**Comment by ecser99** [comment]
entityId: media_player.sonos_bedroom  is already set, but this is does not solve the problem.

The parameter "dontSwitchPlayerWhenGrouping" solved the problem partly (described above under **Steps (OK)** , but I have found a case, where it does not work, described under **Steps (NOT OK):** . 

I think the "dontSwitchPlayerWhenGrouping" parameter should work in both cases, regardless of the sequence of grouping the players, or which player is the master. 


https://github.com/punxaphil/custom-sonos-card/issues/327

**Comment by punxaphil** [comment]
I'm not sure what you are asking for

**Comment by ecser99** [comment]
Let me clarify with this example:
This is the config of sonos media player "Kitchen":

type: custom:sonos-card
entityId: media_player.kitchen
dontSwitchPlayerWhenGrouping: true

The "dontSwitchPlayerWhenGrouping" parameter works well, if Kitchen was the main player in the group and Kitchen is ungrouped. In this case this player shows "Kitchen" after ungrouping. This is OK.

The "dontSwitchPlayerWhenGrouping" parameter does not work, if "Family room" was the main player in the group and Kitchen is ungrouped. In this case this player shows "Family room" after ungrouping. This is the bug.

Expected behaviour: media player Kitchen should show on the player after ungrouping in both cases, even if Kitchen was not the main player in the group.

I hope, this is better understandable now. :-)

**Comment by punxaphil** [comment]
Is this working better? https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.11.2

**Comment by ecser99** [comment]
Yes, with  v7.11.2 it works now as it should. 
Many thanks!
