### ISSUE TITLE
queue section

### ISSUE THREAD

**Issue by Vansmak** [punxaphil/custom-sonos-card#374]
Add a section OR add it to media section to show current queue

At least showing what's next, perhaps be able to manage it.
I currently use a popup card to show the queue and had to use node-red to get it to work 

It's really rudimentary right now
![Screenshot_20240514_180639_Home Assistant](https://github.com/punxaphil/custom-sonos-card/assets/16037573/f93829cd-d229-4621-adb9-3e99b8e6577a)

**Comment by punxaphil** [comment]
How do you get the queue of songs?

**Comment by punxaphil** [comment]
I'd still like to know how you get the queue 🙏

**Comment by Vansmak** [comment]
node-red https://github.com/hklages/node-red-contrib-sonos-plus

**Comment by punxaphil** [comment]
Interesting, I'll take a look!

**Comment by Vansmak** [comment]
stil polishing it but was able to get what i want using stack and conditionals 
![play](https://github.com/punxaphil/custom-sonos-card/assets/16037573/e4c881b5-27ef-468d-8985-c10a9aa69aad)
![queue](https://github.com/punxaphil/custom-sonos-card/assets/16037573/aa6770f4-2b7f-4380-a2c7-3e8c4901251e)
![group](https://github.com/punxaphil/custom-sonos-card/assets/16037573/0ebbdb63-286e-428f-9720-42b51be1f5a7)

**Comment by punxaphil** [comment]
They added support now in the Sonos integration, and because of that we can now show the playlist. It is still in beta state for this card. Please try it out and come with feedback:
https://github.com/punxaphil/custom-sonos-card/releases/tag/v8.0.0-beta2

Closing this issue though, since we have #355
