### ISSUE TITLE
Support Youtube Music Integration

### ISSUE THREAD

**Issue by sweti3** [punxaphil/custom-sonos-card#380]
Hi,

I set up the youtube Music integration:

[KoljaWindeler](https://github.com/KoljaWindeler/ytube_music_player)

The thing is, in the media section, this still is not showing up, but in the standard mediaplayer it is. Do you know why this is so? 

Thanks!

Sven

**Comment by punxaphil** [comment]
Please provide some screenshots

**Comment by punxaphil** [comment]
no response, closing
