### ISSUE TITLE
Renamed rooms not updating

### ISSUE THREAD

**Issue by charlesmcevoy** [punxaphil/custom-sonos-card#386]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
7.11.0

**Last working release (if known):**

**Browser and Operating System:**
Chrome / Windows 10
Android HA Companion App

**Description of problem:**

Room names recently changed in the Sonos App on Android. The changes are reflected correctly in the Sonos App on Windows 10 but are not correct in HA. A Newly created room appears as 'Unknown Room' and the speaker whose room was renamed appears under its previous room name.
Function is otherwise unaffected - everything else works as expected.
 
**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
Redownloading the Card has not helped.

**Comment by punxaphil** [comment]
It is Home Assistant itself who controls this. It keeps the old names. You need to update in the devices section. `/config/devices`
