### ISSUE TITLE
Missing backgrounds in ios-themes

### ISSUE THREAD

**Issue by gaga191281** [punxaphil/custom-sonos-card#395]
I am not really sure if this should be seen as a bug or a feature request.
When using the feature "Artwork as background" the control buttons and the tile information are showing a background to stay visible independent from the cover art.
But when using the ios-themes those backgrounds are missing. I tried to change stuff in the "custom-sonos-card.js" but without any success.
Could you have a look in this issue. Or at least tell me which property in which file is responsible for those backgrounds?

![cover_normal](https://github.com/punxaphil/custom-sonos-card/assets/60061155/696fa7e0-0375-43da-a3ec-eac7b7840283)
![cover_ios](https://github.com/punxaphil/custom-sonos-card/assets/60061155/6884ab95-2180-44ee-b036-47f561f4ccc7)

**Comment by punxaphil** [comment]
The theme you are using is incomplete. But you can use this:
https://community.home-assistant.io/t/dashboard-sonos-card/393620/890?u=punxsutawneyphil
