### ISSUE TITLE
Change volume by scrolling mouse wheel

### ISSUE THREAD

**Issue by NoopNetwork** [punxaphil/custom-sonos-card#421]
# Context
The old Sonos Windows App supported hovering over any volume slider and using the mouse wheel to increase and decrease the volume for the respective speaker. As the new Sonos App is generally lagging a lot of features, including the mouse wheel volume, I exclusively use custom-sonos-card now. Would be great to have the feature here.

# Requested solution
On devices with a mouse, when the user is hovering over any volume slider (master volume in player view, speaker volume in grouping view etc.) and scrolls the mouse wheel up, the volume increases for the respective speaker(s). Scrolling the mouse down decreases the volume respectively.

### Thank you for all the work and a great HA card!!!

**Comment by punxaphil** [comment]
Don't think I'll be able to prioritise this, but if someone wants to contribute, feel free

**Comment by punxaphil** [comment]
Closing it I'm afraid. I am using components from Home Assistant, and it doesn't seem to support mouse scroll: https://github.com/home-assistant/frontend/blob/dev/src/components/ha-control-slider.ts
