### ISSUE TITLE
Volume controls not working

### ISSUE THREAD

**Issue by diddlyhub** [punxaphil/custom-sonos-card#422]
**Checklist:**

- [ x] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:** 7.11.2

**Last working release (if known):**

**Browser and Operating System:** Various.  Edge on windows 11, chrome windows 11, chrome android 14,  Brave android 13

**Description of problem:**
The volume slider and mute button on the card do not work, for whatever reason.

When I change the volume on other media cards, the speaker itself or the Sonos app it update in this card immediately.

I'm using a fully updated HA instance on a RPi4.
The speaker I'm testing against is an Era300.

I've read through the open and closed tickets and see no mention of this issue, so I thought I would raise it.

Any help/advice gratefully received - I'm hoping it's a bug and not an id10t error on my part. Thanks!!

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by vijexa** [comment]
I just had this issue, power-cycling the speaker didn't work, but controls worked in sonos app. I've decided to check browser console after seeing your post. Saw `Player media_player.kitchen is unavailable` there. Tried reloading sonos integration in hass, and it resolved my problem

**Comment by punxaphil** [comment]
Sounds like the right solution, thanks @vijexa
