### ISSUE TITLE
[FR] Fit the Sonos Card into grid system (Section view)

### ISSUE THREAD

**Issue by bieniu** [punxaphil/custom-sonos-card#440]
**Is your feature request related to a problem? Please describe.**

If we use [Section view](https://www.home-assistant.io/dashboards/sections/) (HA 2024.8+), the Sonos Card height does not fit into multiples of row heights:

![obraz](https://github.com/user-attachments/assets/af94d547-225d-429e-b946-b58b22feaced)

**Describe the solution you'd like**

A nice feature would be to fit the Sonos Card into grid system https://www.home-assistant.io/blog/2024/07/26/dashboard-chapter-2/#action-items-what-can-you-do-as-a-custom-card-developer-now
In this case, the Sonos Card should be 9 rows high.

```yaml
layout_options:
  grid_columns: 4
  grid_rows: 9
```

**Comment by punxaphil** [comment]
I honestly don't understand the section view system at all. I tried following the developer guide, but it doesn't make a difference if I implement `getLayoutOptions` or not. And, yes, I have tried with the new Sections setting for the dashboard.
