### ISSUE TITLE
 Source map error - Source Map URL: custom-sonos-card.js.map #145 

### ISSUE THREAD

**Issue by johntdyer** [punxaphil/custom-sonos-card#441]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**
7.11.2

**Last working release (if known):**

**Browser and Operating System:**
Firefox OSX 129.0 (64-bit)

**Description of problem:**

Noticed this warning in my logs, not sure how to resolve it 

**Javascript errors shown in the web inspector (if applicable):**

```
Source map error: request failed with status 404 Resource URL: https://xxxxxx/hacsfiles/custom-sonos-card/custom-sonos-card.js?hacstag=4494168166101 Source Map URL: custom-sonos-card.js.map
```

**Additional information:**

**Comment by punxaphil** [comment]
If anyone still saw these errors, I hope they are fixed now with this:

https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.21.3
