### ISSUE TITLE
Allow "Browse media" button on the main pane of the card

### ISSUE THREAD

**Issue by Stooovie** [punxaphil/custom-sonos-card#448]
Please provide a way to have the "Browse media" on the main page of the card. As of now, user has to click the Star icon first, which seems unnecessary.

**Comment by punxaphil** [comment]
https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.12.0
---
PunxaPhil
[![image](https://github.com/johanfrick/custom-sonos-card/assets/26582898/9bebc1f6-6bda-4cbd-b596-50d3d2f712de)](https://www.buymeacoffee.com/punxaphil)
