### ISSUE TITLE
Sonos group volume sync player volume offset - is there any way to do this?

### ISSUE THREAD

**Issue by peteypauls** [punxaphil/custom-sonos-card#453]
Hello.  I just got the new Sonos Card and it's awesome. Full of functionality.  One thing I've noticed is that when I raise/lower the slider for "All" volumes when I am in a group, all of the speakers jump to that volume instead of being offset like the Sonos app.  I have different speakers and different rooms and they all start at different set levels.  Would be great to have this functionality.  

In mini media player I was able to offset the volumes, not sure if this is the best way to do this.  

- entity_id: media_player.family_room_sonos
      name: Family Room "this syncs with the master so no need for adjustment"
    - entity_id: media_player.kitchen_sonos
      name: Kitchen
      volume_offset: 11 "11 levels louder than the master"
    - entity_id: media_player.bedroom_sonos
      name: Bedroom
      volume_offset: 18 "18 levels louder than the master"
    - entity_id: media_player.bathroom_sonos

**Comment by punxaphil** [comment]
Have you read the documentation? 🙂
`adjustVolumeRelativeToMainPlayer`
