### ISSUE TITLE
[NSPanel] only shows digit for favorites

### ISSUE THREAD

**Issue by Beerpassion** [punxaphil/custom-sonos-card#460]
**Checklist:**

- [ X] I updated to the latest version available
- [ X] I cleared the cache of my browser

**Release with the issue:**
2.0.1
**Last working release (if known):**
Previously never had issues, not sure about exact version
**Browser and Operating System:**
NSPanel pro browser 
There are no issues on mobile HA App or regular PC browsers

**Description of problem:**
On the favorites tab it only show the digit for number of favorites e.g. 4 

Normal browser works ok:
![image](https://github.com/user-attachments/assets/466a9747-3012-4635-ae8b-69dc68f7f2ab)

On the NSPanel this worked before but now get this:
![image](https://github.com/user-attachments/assets/e8514f5b-07e9-44ad-a32c-3b98c926ee3b)

The digit corresponds with the number in the configuration "**_Media Browser Items Per Row_**" actually
![image](https://github.com/user-attachments/assets/b2df8efe-5c3d-4168-b16a-255cffcfeb94)

**Comment by punxaphil** [comment]
release 2.0.1??
The latest version of this card is 7.11.2

**Comment by Beerpassion** [comment]
hi,

Sorry, you are right I noted the wrong number from the new HACS.
The latest release is installed:
[image: image.png]

Op di 10 sep 2024 om 20:24 schreef Punxa Phil ***@***.***>:

**Comment by peteypauls** [comment]
Can you upgrade your OS?  not sure if it helps, but I had the same issue on my Mac until I updated the OS a few days ago.

**Comment by maltorfer** [comment]
I have the same problem also on Sonoff NSPanel pro. Used to work before.

**Comment by mistergyle** [comment]
same issue for me...

**Comment by punxaphil** [comment]
Does https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.11.3 make any difference?

**Comment by maltorfer** [comment]
> Does https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.11.3 make any difference?

No. Doesn't change anything.

**Comment by punxaphil** [comment]
try 2: https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.11.4-beta
(you need to enable beta in HACS to see it)

**Comment by maltorfer** [comment]
> try 2: https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.11.4-beta (you need to enable beta in HACS to see it)

Nope. doesn't solve. Perhaps you build in some debug output?

**Comment by punxaphil** [comment]
https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.11.4-beta2
?

**Comment by maltorfer** [comment]
> https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.11.4-beta2 ?

Doesn't work.
In previous versions, you could set "Media Browser Items Per Row" to 0 and it would display a list of favorites without icon. Now you can't select '0', minimum is 1 and nothing is shown except the number you selected in the media browser items per row selection (like before).

**Comment by punxaphil** [comment]
What's your card config?
What do you see in the web debug console?

**Comment by maltorfer** [comment]
> What's your card config? What do you see in the web debug console?

I don't have access to the web console; the device is running home assistant compagnion app (android-minimal).

Config:

type: custom:sonos-card
sections:
  - groups
  - grouping
  - media browser
  - player
  - volumes
widthPercentage: 100
heightPercentage: 85
topFavorites:
  - ''
dynamicVolumeSlider: true
dynamicVolumeSliderMax: 50
dynamicVolumeSliderThreshold: 100
hideGroupCurrentTrack: false
mediaBrowserHideTitleForThumbnailIcons: false
mediaBrowserItemsPerRow: 1
showVolumeUpAndDownButtons: false
hideBrowseMediaButton: false

**Comment by punxaphil** [comment]
Try removing this:

topFavorites:
  - ''

**Comment by maltorfer** [comment]
Doesn't change anything.

best,
Martin

**Comment by christopherhahlbeck** [comment]
Same Problem here. 
Just showing "3" instead of favorites. 
On Phone, iOS App, Windows (Browser) everything is fine. 
Only occures on Sonoff nspanel pro and Shelly Wall Display.

**Comment by christopherhahlbeck** [comment]
Habe jetzt mal downgrades bis zur Version 7.0.0 gemacht. Da funktioniert es auch nicht. 
Sieht so aus als ob der "bug" schon immer drin wäre, aber erst mit einem HA update auswirkungen hatte

**Comment by punxaphil** [comment]
What makes you think I understand German!?😅

**Comment by christopherhahlbeck** [comment]
> What makes you think I understand German!?😅

There are tools called „translator“ 😂

I have now downgraded to version 7.0.0. Onw by One. It doesn't work there either. It looks like the 'bug' has always been present but only had an effect after a HA update.

**Comment by punxaphil** [comment]
Maybe the bug is not in the card but home assistant introduced a bug in recent versions?

**Comment by christopherhahlbeck** [comment]
I dont think so 😂
100% the bug is in the card, otherwise this would not be present for months or you can find something similar to this

**Comment by christopherhahlbeck** [comment]
Maybe i could. But i dont care and this is your job, just wanted to help the other one. 
i dont use the card on these displays. So good luck.

**Comment by MaTr75** [comment]
I have the same problem with the Shelly WallDisplay. The WD now can display home assistant dashboards with new beta firmware.

I assume that the error may occur here: I activated "replaceHttpWithHttpsForThumbnails: true" but it seems, that nevertheless https is used for the icons on the "Favorites" tab.

**Comment by punxaphil** [comment]
`replaceHttpWithHttpsForThumbnails` means that it will always use https, not the other way around.
I can't see how that relates to it displaying a digit instead of actual favourites. Can you explain why you think that?

**Comment by MaTr75** [comment]
ah... ok... I was wrong. I thought it was the other way round and https was replaced with http.

But otherwise: The icons have by default a https-Url. Might that be the problem?

**Comment by punxaphil** [comment]
Doesn't sound likely, but hard to be certain. Can you inspect the html and see what is rendered?

**Comment by MaTr75** [comment]
no. on the WallDisplay I don´t know how to get access to the html source.

But in the Chrome-Browser on my MacBook I get some insights.
![Uploading Bildschirmfoto 2024-10-04 um 20.08.35.png…]()

**Comment by punxaphil** [comment]
I think your image upload failed

**Comment by MaTr75** [comment]
sorry. Now it works

**Comment by punxaphil** [comment]
Thanks. Not sure that helps me though...

**Comment by zitroaen** [comment]
> sorry. Now it works

Did you find out, what the issue is? I have the same problem on Shelly Wall Display. 

What I found interesting is, that if I enter `mediaBrowserItemsPerRow: 1`, all titles are shown - with blank spaces where the Artwork should be. If I set this to anything but 1, it just shows the number. 


Does anyone know whether there is a way to debug on the Shelly Wall Display? 
Thanks! :)

**Comment by MaTr75** [comment]
> > sorry. Now it works
> 
> Did you find out, what the issue is? I have the same problem on Shelly Wall Display.

My comment was related to the missing upload. I still have the problem that we discuss here. I can confirm that setting the mediaBrowserItemsPerRow to 1 lead to the interesting behavior that the Labels of the favorite stations are displayed but still not the icons.

**Comment by zitroaen** [comment]
OK, gotcha. 

I looked at the source code and saw this section in sections/media-browser.ts:
```javascript
const itemsPerRow = this.config.mediaBrowserItemsPerRow || 4;
            if (itemsPerRow > 1) {
              return html`
                <sonos-media-browser-icons
                  .items=${items}
                  .store=${this.store}
                  @item-selected=${this.onMediaItemSelected}
                ></sonos-media-browser-icons>
              `;
            } else {
              return html`
                <sonos-media-browser-list
                  .items=${items}
                  .store=${this.store}
                  @item-selected=${this.onMediaItemSelected}
                ></sonos-media-browser-list>
              `;
            }
          } 
``` 

So basically this explains, why the two cases of one or multiple Items per row are handled differently (one as a "sonos-media-browser-list" and one as "sonos-media-browser-icons"). 

**Conclusion 1: "sonos-media-browser-icons" does not seem to be working on the Shelly wall display.** 

Interestingly neither one is showing any images. I would therefore guess that:
**Conclusion 2: we are dealing with two separate bugs. One that stops the icons to be created and one that stops the images to be displayed.**

The Favorites overview is pulling the images from https://i.scdn.co/image/[...]

There are also multiple places, where the Artwork is displayed just fine in the Card on the Shelly Wall Display:
- The "currently playing" Artwork in the player: I noticed that this is provided to the browser (at least on my laptop) as a base64 encoded image. My next working theory was, that maybe the Shelly Wall display was not able to make the call to i.scdn.co - however:
- When browsing the favorites in the media browser (click on top right corner), the artwork is also pulled as a background image from i.scdn.co - so basically the same technique as in the initial "overview" where it is not working

**Conclusion 3: I am confused, why it is sometimes working and sometimes not.**

**Comment by snozzlebert** [comment]
I've the same issue on a Xiaomi Mi Smart Clock (Android 13, Webview 107.0.5304.91). Laptop works.

**Comment by punxaphil** [comment]
After many, many hours of trying to fix this, I believe I finally solved it.
I hope you are able to show your support and your appreciation for my work through patreon or buymecoffee 🙏 

---
PunxaPhil
[![image](https://github.com/user-attachments/assets/cb2e240e-f9ca-4900-a425-b8089216c1ee)](https://patreon.com/PunxaPhil) [![image](https://github.com/johanfrick/custom-sonos-card/assets/26582898/9bebc1f6-6bda-4cbd-b596-50d3d2f712de)](https://www.buymeacoffee.com/punxaphil)

**Comment by zitroaen** [comment]
Hi punxaphil,

everything works like a charm now! Thank you for your effort!

**Comment by KrisHoobergs** [comment]
Hi,
I see that you all have the sonos card working on you NS Panel Pro.  Today I installed the sonos card, and it shows the following error "custom element doesn't exist: sonos-card."  I'm wondering if one of you also ran into this problem.  I'm running the companion app on my panel, maybe that is the reason?  Maybe it is only working on fully kiosk?  Can you please let me know how you guys are using it or solved this issue.
Thanks
Kris
