### ISSUE TITLE
Ability to add static cover art for playlists, specifically Apple Music playlists in Sonos.  

### ISSUE THREAD

**Issue by peteypauls** [punxaphil/custom-sonos-card#461]
Hello, I may have a specific use case here, so any help is appreciated.  The challenge I have is my Apple Music customized playlists.  I have uploaded pictures for each within Apple Music and they are consistently seen within the Sonos app.  however, in both Sonos card and the media section, they stay there for a day  and then are removed.  It seems that the image is pulled from a blob URL at apple, which is temporary and not cached within home assistant.  

is there a way to somehow link to specific images, perhaps local files, to be shown in the favorites section?

**Comment by punxaphil** [comment]
Have you read the docs? 😉 
`mediaArtworkOverrides`

**Comment by peteypauls** [comment]
Thank you Phil.  your help is appreciated.  I did, then realized it was actually customThumbnail since it was a media browser issue.  it works great for URLs but is there any way to pull local images? 

I have tried: 
1) local/image.png 
2) /local/image.png
3) playlist:
    - image: local/image.png

but nothing is showing up.  wondering if it has to do with the size.
