### ISSUE TITLE
Feature Request: Show Attribute media_playlist in Player

### ISSUE THREAD

**Issue by Acgua** [punxaphil/custom-sonos-card#483]
First of all, thank you so much for your great work!

**Describe the solution you'd like**
With release [v7.13.0](https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.13.0), following feature has been added:
* make it possible to show media channel (e.g. radio station name)

It would be great if you could also add an option to show the `media_playlist` attribute.

Example: When I play the Sonos favorite "Jazz Vibes", which is a public Spotify playlist, it does not show "Jazz Vibes", but just the title, album artist:
![image](https://github.com/user-attachments/assets/7294adec-ee88-442f-b113-74287457d98f)

"Home Assistant > Developer Tools > States" is showing following attributes (extract) of the Sonos device:
```
media_content_id: x-sonos-spotify:spotifyXXXXXXXXXXXXX
media_content_type: music
media_title: Como
media_artist: SamuW
media_album_name: Como
media_playlist: Jazz Vibes
```

Thank you!

**Comment by punxaphil** [comment]
https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.14.0
