### ISSUE TITLE
Default player display for sonos groups

### ISSUE THREAD

**Issue by tomjpeg** [punxaphil/custom-sonos-card#490]
**Is your feature request related to a problem? Please describe.**
When using a group in Home Assistant, the group entity doesn't provide current song information, making it impossible to see what's playing when using the group entity in the Sonos card. This forces users to either use individual players or miss out on current media information.

**Describe the solution you'd like**
I would like the ability to specify a default player to display in the Sonos card while still controlling a group. For example, if I have a group consisting of living room, kitchen, and office speakers, I'd like to be able to:

Control all speakers as a group
Display the current song information from a specific player (e.g., living room)
Still see and control group functionality

This would combine the benefits of group control with the detailed information of individual players.

**Describe alternatives you've considered**
Using individual players instead of groups (loses the convenience of group control)
Creating automations to update group information (complex and not reliable)
Using different media player cards (lose Sonos-specific features)

**Additional context**
This feature would be particularly useful for users with multiple Sonos speakers who frequently use them as groups but still want detailed playback information. It would enhance the user experience by providing both group control and detailed media information in one interface.

**Comment by tomjpeg** [comment]
If this is already possible, please excuse me. I would appreciate an explanation on how to do it.

**Comment by punxaphil** [comment]
If you want to show the living room player's information, just make sure to make that player the main player.
This is done by going to that player and then start grouping from there.
If you are using `predefinedGroups`, make sure living room player is the first one in the list.
