### ISSUE TITLE
Entity from Template

### ISSUE THREAD

**Issue by mattmeiser** [punxaphil/custom-sonos-card#497]
**Is your feature request related to a problem? Please describe.**
I have some buttons on a dashboard that automatically group different Sonos units and play a favorite.   Depending on what's playing, I'd like to force the Sonos card to use a specific player as the master entity.    

**Describe the solution you'd like**
I'd like to see this work:

`playerVolumeEntityId: |
              {% if is_state("media_player.patio_sonos", "playing") -%}
                media_player.patio_sonos
              {%- else -%}
                media_player.kitchen_sonos
              {%- endif %}
            entityId: |
              {% if is_state("media_player.patio_sonos", "playing") -%}
                media_player.patio_sonos
              {%- else -%}
                media_player.kitchen_sonos
              {%- endif %}    `

**Describe alternatives you've considered**
The card sometimes seems to pick up a new group but definitely not reliably.

**Comment by punxaphil** [comment]
> automatically group different Sonos units and play a favorite

This feature is already built into the sonos card. And if you click those buttons it will select the right player.
Use `predefinedGroups` along with `media`.
