### ISSUE TITLE
problem with skipApplyButtonWhenGrouping

### ISSUE THREAD

**Issue by ojm88** [punxaphil/custom-sonos-card#498]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

Hello. I'm experiencing a problem with audio groups. It looks like the first group you create works on activation. The groups that are 2-3, etc., are unable to connect together. I have video of the problem if anyone wants it?

**Comment by punxaphil** [comment]
Please share the video

**Comment by ojm88** [comment]
https://github.com/user-attachments/assets/6e693c75-576e-4894-a738-63c6ae4b1b71

**Comment by ojm88** [comment]
Thank you for your involvement in my problem.
Am I the only one experiencing this problem? This is such an important functionality in the sonos card

**Comment by punxaphil** [comment]
Yes, to me it feels like an issue with your players/your sonos setup. This usually works for users without problems.

**Comment by ojm88** [comment]
Hello. It works to group speakers with HA's own join option service call, and Sonos' original app. 

I experience a much more stable grouping in the Sonos card, if the option "Skip Apply Button When Grouping" is switched off. But when this option is turned on, the problems start.

**Comment by punxaphil** [comment]
Please share your cardconfig yaml

**Comment by punxaphil** [comment]
@cryptk @ojm88 
I could reproduce some shaky grouping as well when using `skipApplyButtonWhenGrouping: true`. 
The following fix made it more stable for me, let me know how it works for you!
https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.21.4

**Comment by cryptk** [comment]
Seems to be working now! Thanks!

**Comment by punxaphil** [comment]
Great!
If you have the possibility, please contribute for further development 🙏 


---
PunxaPhil
[![image](https://github.com/user-attachments/assets/cb2e240e-f9ca-4900-a425-b8089216c1ee)](https://patreon.com/PunxaPhil) [![image](https://github.com/johanfrick/custom-sonos-card/assets/26582898/9bebc1f6-6bda-4cbd-b596-50d3d2f712de)](https://www.buymeacoffee.com/punxaphil)
