### ISSUE TITLE
Entity settings are beeing ignored

### ISSUE THREAD

**Issue by MaTr75** [punxaphil/custom-sonos-card#499]
I have updated to 7.17 an my entity setting don't work anymore. I only want to use five rooms in Sonos card and exclude all the rest. Till now I achieved that with following config:

        entities:
          - media_player.bad
          - media_player.wohnzimmer
          - media_player.schlafzimmer
          - media_player.kuche
          - media_player.roam
        entitiesToIgnoreVolumeLevelFor:
          - media_player.wohnzimmer
          - media_player.kuche

Since 7.17 *all* rooms are displayed a not only the five rooms that are configured. The "entitiesToIgnoreVolumeLevelFor" section works. In these two rooms the volume can not be changed. But all other rooms are displayed now.

**Comment by punxaphil** [comment]
Thanks for reporting. Looks like i introduced a bug. I'll investigate.

**Comment by punxaphil** [comment]
Can try which other version it works with?

**Comment by MaTr75** [comment]
I think with 7.15 it worked perfectly

**Comment by alexio70** [comment]
> I have updated to 7.17 an my entity setting don't work anymore. I only want to use five rooms in Sonos card and exclude all the rest. Till now I achieved that with following config:
> 
> ```
>     entities:
>       - media_player.bad
>       - media_player.wohnzimmer
>       - media_player.schlafzimmer
>       - media_player.kuche
>       - media_player.roam
>     entitiesToIgnoreVolumeLevelFor:
>       - media_player.wohnzimmer
>       - media_player.kuche
> ```
> 
> Since 7.17 _all_ rooms are displayed a not only the five rooms that are configured. The "entitiesToIgnoreVolumeLevelFor" section works. In these two rooms the volume can not be changed. But all other rooms are displayed now.

Same issue here; also the excludeItemsInEntitiesList: true is being ignored

**Comment by punxaphil** [comment]
Should be fixed here: https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.17.1


---
PunxaPhil
[![image](https://github.com/user-attachments/assets/cb2e240e-f9ca-4900-a425-b8089216c1ee)](https://patreon.com/PunxaPhil) [![image](https://github.com/johanfrick/custom-sonos-card/assets/26582898/9bebc1f6-6bda-4cbd-b596-50d3d2f712de)](https://www.buymeacoffee.com/punxaphil)
