### ISSUE TITLE
Album Art will not show an Google Nest Hub

### ISSUE THREAD

**Issue by DieBreuers** [punxaphil/custom-sonos-card#500]
Hi,
Im new to HA. Ive seen this nice Template and would like to use ist on my Nest Hubs. 
It works really well, but at my Nest Hubs the Album Cover will not be shown. 
The Titel and so will be shown. 
In HA there is no problem and looks nice. 
Im using Apple Music. 
I Think I've got a mistake but i don't know why. 
There must be a difference between Mac or running an my Nest devices. 
The Picture shows the Lenovo with a Placeholder Artwork.

- [ X] I updated to the latest version available
- [X ] I cleared the cache of my browser

OSX 11.7.10 , Safari, Firefox 
Google Nest Hub 2, Lenovo Smart Display 8"

![LenevoSonosCard](https://github.com/user-attachments/assets/b69df6c2-ff87-4629-9fe5-5c0a14ae70ae)

**Comment by punxaphil** [comment]
No idea how to solve this I am afraid. Also I don't have this unit which makes it even harder.

**Comment by DieBreuers** [comment]
Okay I understand. 
Ive tried it with other devices and it happens with my 2 other  Google Nest Hubs, too.

**Comment by DieBreuers** [comment]
Ive looked around some forums. 
I see that some other Users got the same problem with showing the Album Art. 
https://community.home-assistant.io/t/casting-my-music-dashboard-album-art-is-replaced-by-generic-image/477013
Someone has written that he found out that the problem will be the reference URL in the Artwork . 
Here a possible solution: 
"This URL is HA local adress. I made a fork of the custom-sonos-card where i added my local HA IP adress as a prefix to the enity_picture url and this made the nesthub show the artwork.
If the enity_picture url would be http://[HA-IP]:8123[entity_picure_url_as_of_now] it should work on the nesthub."

Can you give me a tip where I can make the change? Im an IT Man but not in the programming are :-)
In the Studio Code Server I searched, but can't find the Place... 
Or can some one Other give me a Tip?
Thank you very much.

**Comment by punxaphil** [comment]
Sorry, I totally forgot we already have an solution for this: https://github.com/punxaphil/custom-sonos-card/pull/110
