### ISSUE TITLE
Use `entity_picture` instead of `media_content_id` in media browser

### ISSUE THREAD

**Issue by bdsoha** [punxaphil/custom-sonos-card#501]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** `v7.17.1`

**Browser and Operating System:** 
- Safari / MacOS
- Chrome / MacOS
- Chrome / Windows

**Description of problem:**

Artwork images on the *media browser* page return a `404` error when attempting to fetch 
from `https://my-domain/getaa?u=x-file-cifs`.
The image path is defined by the `media_content_id` attribute.

In contrast, the player page uses the `entity_picture` attribute, and the corresponding URL 
`https://my-domain/api/media_player_proxy/media_player.MEDIA_PLAYER?token=TOKEN` works correctly.

**Comment by punxaphil** [comment]
The list of favorites is not found on the player's attributes. They have to be fetched by calling the `media_player/browse_media` service. This service call does not return entity_picture, it returns thumbnail.
Example:
<img width="543" alt="image" src="https://github.com/user-attachments/assets/d656548b-7798-4076-bdc3-6a395867e7ac">

**Comment by bdsoha** [comment]
Are you familiar with others that had issues displaying Sonos favorites?

**Comment by punxaphil** [comment]
No

**Comment by bdsoha** [comment]
Thanks!
