### ISSUE TITLE
Spotify Favorites

### ISSUE THREAD

**Issue by Aham330** [punxaphil/custom-sonos-card#503]
Very nice integration. 

I was wondering if it were possible to have the Spotify favorites listed in the favorites section?

Kind regards

**Comment by punxaphil** [comment]
Either you need to add favorites in the official Sonos app, or use `customSources`: https://github.com/punxaphil/custom-sonos-card?tab=readme-ov-file#custom-favorites--sources

**Comment by Aham330** [comment]
Hi Phil,

Have to say very nice integration! Thanks for designing and creating it.

I indeed tried both your suggestions which both work. It would be nice though if there were a way, to more easily import the playlist from Spotify with the associated album art iso going through Sonos app or url. Sadly I myself do not have enough know how to be able to help create such a feature.

**Comment by punxaphil** [comment]
I agree it would be nice. That should be built in the backend though, so make your request here: https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sonos%22

**Comment by Aham330** [comment]
ok will do that, thank you.
