### ISSUE TITLE
Change New Icons

### ISSUE THREAD

**Issue by SPESINO** [punxaphil/custom-sonos-card#513]
First of all, thank you for your excellent work. I am going to propose if it were possible to change the general menu icons. Will it be possible? Thank you.

![IMG_9427](https://github.com/user-attachments/assets/4c71d3f1-d654-4348-8876-36dbd400585e)

**Comment by punxaphil** [comment]
https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.20.1
```
sectionButtonIcons: # customize icons for the section buttons
  player: mdi:ab-testing
  mediaBrowser: mdi:star-box-multiple
  groups: mdi:multicast
  grouping: mdi:group
  volumes: mdi:volume-high
  ```


---
PunxaPhil
[![image](https://github.com/user-attachments/assets/cb2e240e-f9ca-4900-a425-b8089216c1ee)](https://patreon.com/PunxaPhil) [![image](https://github.com/johanfrick/custom-sonos-card/assets/26582898/9bebc1f6-6bda-4cbd-b596-50d3d2f712de)](https://www.buymeacoffee.com/punxaphil)
