### ISSUE TITLE
Add a Favorite Button

### ISSUE THREAD

**Issue by swimminshell** [punxaphil/custom-sonos-card#514]
**Is your feature request related to a problem? Please describe.**
It seems that it is not possible to save a track to Deezer favorites.

**Describe the solution you'd like**
would it be possible to enhance the plugin so that we can save the currently playing music directly to the Deezer favorites?

thank you

**Comment by punxaphil** [comment]
I don't see any backend support for Deezer in Home Assistant I am afraid
