### ISSUE TITLE
Martín Top. 

### ISSUE THREAD

**Issue by SPESINO** [punxaphil/custom-sonos-card#520]
Hi there. Here I come with a new idea. Would it be possible to adjust the top margin of the elements, since if we have many speakers we have to scroll and it is complicated. Thanks in advance.

![IMG_9493](https://github.com/user-attachments/assets/601ced7f-ba0f-4d98-9b2e-a1c8418b25e8)

**Comment by punxaphil** [comment]
https://github.com/punxaphil/custom-sonos-card?tab=readme-ov-file#example-1---reduce-margin-for-grouping-list-items


---
PunxaPhil
[![image](https://github.com/user-attachments/assets/cb2e240e-f9ca-4900-a425-b8089216c1ee)](https://patreon.com/PunxaPhil) [![image](https://github.com/johanfrick/custom-sonos-card/assets/26582898/9bebc1f6-6bda-4cbd-b596-50d3d2f712de)](https://www.buymeacoffee.com/punxaphil)
