### ISSUE TITLE
Clear Queue / Playlist button as an option?

### ISSUE THREAD

**Issue by psjnr84** [punxaphil/custom-sonos-card#531]
Hi Team,

Could I potentially find out if you could add an option to the new queue functionality screen to clear the queue on the selected player?

I’m currently having to do this on a room by room basis with a custom button under each instance of the player. It would be great if your code could invoke this dynamically when you are on each Sonos device.

Given your code can be targeted against each instance of a Sonos device, could you extend it just to include a clear queue / playlist function as well?

**Comment by punxaphil** [comment]
Please share yaml of your custom button

**Comment by psjnr84** [comment]
- type: custom:mushroom-select-card
    entity: input_select.sonos_media_player
    name: Select Media Player
    layout: horizontal
    hold_action:
      action: none
    double_tap_action:
      action: none
    primary_info: name
    secondary_info: none
  - type: conditional
    conditions:
      - condition: state
        entity: input_select.sonos_media_player
        state: Lounge
    card:
      type: custom:mushroom-template-card
      primary: ""
      secondary: Clear Lounge Queue
      icon: ""
      layout: vertical
      tap_action:
        action: perform-action
        perform_action: media_player.clear_playlist
        target:
          entity_id: media_player.lounge_sonos
      hold_action:
        action: none
      double_tap_action:
        action: none
  - type: conditional
    conditions:
      - condition: state
        entity: input_select.sonos_media_player
        state: Master
    card:
      type: custom:mushroom-template-card
      primary: ""
      secondary: Clear Master Queue
      icon: ""
      layout: vertical
      tap_action:
        action: perform-action
        perform_action: media_player.clear_playlist
        target:
          entity_id: media_player.master_sonos
      hold_action:
        action: none
      double_tap_action:
        action: none
  - type: conditional
    conditions:
      - condition: state
        entity: input_select.sonos_media_player
        state: Guest
    card:
      type: custom:mushroom-template-card
      primary: ""
      secondary: Clear Guest Queue
      icon: ""
      layout: vertical
      tap_action:
        action: perform-action
        perform_action: media_player.clear_playlist
        target:
          entity_id: media_player.guest_bedroom
      hold_action:
        action: none
      double_tap_action:
        action: none

**Comment by psjnr84** [comment]
input_select.sonos_media_player

The input select option has three values (in my case, Lounge / Master / Guest) which change the conditional card value on what is shown based on this. 

It would be great to have the ability to have the clear media playlist function fully integrated into your card, allowing me to be able to remove this code and free up space on my dashboard.

**Comment by psjnr84** [comment]
Thanks Phil - much appreciated for doing this. Saves me some work across new clients when implementing this along with my own dashboards.

**Comment by punxaphil** [comment]
Please try this one: https://github.com/punxaphil/custom-sonos-card/releases/tag/v8.0.0-beta4

---
PunxaPhil
[![image](https://github.com/user-attachments/assets/cb2e240e-f9ca-4900-a425-b8089216c1ee)](https://patreon.com/PunxaPhil) [![image](https://github.com/johanfrick/custom-sonos-card/assets/26582898/9bebc1f6-6bda-4cbd-b596-50d3d2f712de)](https://www.buymeacoffee.com/punxaphil)

**Comment by psjnr84** [comment]
Works like a dream. Thank you very much for the quick turnaround!
