### ISSUE TITLE
Favorites view only showing single letters

### ISSUE THREAD

**Issue by beeeeswax** [punxaphil/custom-sonos-card#535]
**Checklist:**

- [✓] I updated to the latest version available
- [✓] I cleared the cache of my browser

**Release with the issue:** 8.0.0

**Last working release (if known):** Unknown

**Browser and Operating System:** Android app 2024.10.3 / Chrome 130 Windows

**Description of problem:**  I can't remember what version this started on but for a while now, the All Favorites view has been broken for me, it looks [like this](https://i.imgur.com/yLXFbH6.png). What did I do?  I thought perhaps I'd added too many favorites but I deleted a load today and it still looks like that.

Same on Android and Windows and I've tried clearing the cache on both.  If I drill down into [Browse Media] -> [Favorites] the individual sections all appear to work properly so the card can obviously read and parse my favorites, but the main overview is just not working for me for some reason.

HA 2024.11.1 running in a VMWare VM (HAOS)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by punxaphil** [comment]
Share your card config, please.

**Comment by beeeeswax** [comment]
Hey punxaphil, I only configured it as far as necessary to get it to see my Sonos devices.  Is this the config you mean?

`type: custom:sonos-card
sections:
  - player
  - volumes
  - groups
  - grouping
  - media browser
showVolumeUpAndDownButtons: true
topFavorites:
  - ""
dynamicVolumeSlider: true
mediaBrowserItemsPerRow: 24
showAudioInputFormat: true
volumeStepSize: 1
numberOfFavoritesToShow: 10
favoritesItemsPerRow: 3
`
Reducing numberOfFavoritesToShow was only done as part of troubleshooting, I thought maybe if I limited it to a low number, I'd be able to see the items properly but it didn't help.

**Comment by punxaphil** [comment]
`mediaBrowserItemsPerRow: 24`
This is the problem. You are trying to show 24 items per row. Reduce that number and it will look correct.


---
PunxaPhil
[![image](https://github.com/user-attachments/assets/cb2e240e-f9ca-4900-a425-b8089216c1ee)](https://patreon.com/PunxaPhil) [![image](https://github.com/johanfrick/custom-sonos-card/assets/26582898/9bebc1f6-6bda-4cbd-b596-50d3d2f712de)](https://www.buymeacoffee.com/punxaphil)

**Comment by beeeeswax** [comment]
omg I'm so sorry.  I also have no idea how or why I would have set that!  I've set it back down to 3 and all working as normal now, thank you!
