### ISSUE TITLE
Sleep Timer

### ISSUE THREAD

**Issue by UkeHa** [punxaphil/custom-sonos-card#540]
I have a Sonos in my bed room and use it to listen to music/podcasts. Currently i use the sonos app to set a sleep timer for 15-30 minutes so the music turns off automatically as soon as i sleep.

I'd like to have a button to set/remove/add a sleep timer. It'd be fine if it is hidden in the settings menu on the bottom left corner, as it's not a much used feature.

**Comment by UkeHa** [comment]
@punxaphil works for me! An Indicator that a sleep timer is running and a time remaining would be cool too. Also perhaps a slider in Minutes that sets the seconds value?

**Comment by punxaphil** [comment]
That information isn't available I'm afraid in Home Assistant.
I'll consider minutes.

**Comment by sanderlv** [comment]
Where can I find the sleep timer config? Cant see it in docs and not in my card config.

**Comment by punxaphil** [comment]
> Where can I find the sleep timer config? Cant see it in docs and not in my card config.

No config required. Just make sure you have v8.1, then go to volumes section.

**Comment by sanderlv** [comment]
Have 8.1.1 and don't see it...

**Comment by punxaphil** [comment]
Share a video or screenshot please

**Comment by sanderlv** [comment]
Will try. I have 7 rows. "All" and 6 single. No other lines

**Comment by punxaphil** [comment]
you need to click the cogwheel

**Comment by UkeHa** [comment]
works on desktop but not in the mobile app (tested with v. 8.1.1):

Desktop:
![grafik](https://github.com/user-attachments/assets/bbb9c074-24cf-43f3-8d9f-9665107a2060)

Android App:
![Mobile](https://github.com/user-attachments/assets/4e23b1c8-143d-4cd8-80ae-85a2a4f963dd)

**Comment by punxaphil** [comment]
I'm sure it's some cache issue on your device.
Here's my mobile app
![image](https://github.com/user-attachments/assets/69ca2257-ac32-4e47-ab84-c67c737c60c3)

**Comment by UkeHa** [comment]
You're right, killing the app completely fixes it

**Comment by sanderlv** [comment]
Cogwheel it is...

But I need to set it 6 times then 🙈

**Comment by sanderlv** [comment]
For reasons I have 1 speaker per group. 

Cause your app makes it work to select where to play very granular then!
