### ISSUE TITLE
High CPU Load with Sonos Card v8.2.0

### ISSUE THREAD

**Issue by gregwjacobs** [punxaphil/custom-sonos-card#547]
**Checklist:**

- [X ] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**

8.2.0 

**Last working release (if known):**

8.1.1

**Browser and Operating System:**

**Description of problem:**

High CPU load within HASS, had to revert to prior version of sonos card to resume normal operation. Traced issue back to this sonos-card HACS add on. 

Let me know what logs I can gather for you. 

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by punxaphil** [comment]
Please share your card config. 
The changes in 8.2.0 compared to 8.1.1 are minimal. Hard to see any issues like this have been introduced with that release.

**Comment by gregwjacobs** [comment]
```
type: custom:sonos-card
sections:
  - player
  - volumes
  - groups
  - grouping
  - media browser
showVolumeUpAndDownButtons: true
showFastForwardAndRewindButtons: true
mediaArtworkOverrides: []
topFavorites:
  - ""
showAudioInputFormat: true
artworkAsBackground: false
heightPercentage: 75
```

**Comment by gregwjacobs** [comment]
I was not able to reproduce this, and newer versions don't show the issue. I suspect I wrongly correlated the sonos card to other restarts cause / clearing my issue. Closing for now.

**Comment by gregwjacobs** [comment]
Can't reproduce, can't determine if component here at fault.
