### ISSUE TITLE
Card Mod to style browser section - "Example 7" from readme does not work

### ISSUE THREAD

**Issue by somansch** [punxaphil/custom-sonos-card#555]
**Release with the issue:**
v8.3.0

**Last working release (if known):**
not known

**Description of problem:**

"Example 7" in readme describes the customization of browser section. Unfortunately, the given example for padding does not work:
`card_mod:
  style:
    sonos-media-browser$: |
      .button {
        --control-button-padding: 4px;
      }`

I want to change these two entries:
--control-button-padding: 16px
--control-button-background-color: transparent

Card_mod is working in general as I was able to customize these two other settings successfully:
`card_mod:
  style:
    sonos-media-browser$: |
      sonos-media-browser-header {
        display: none;
      }
      sonos-media-browser-icons {
        --rgb-card-background-color: transparent;
      }`

**Comment by punxaphil** [comment]
Thanks for reporting! Fixed:
https://github.com/punxaphil/custom-sonos-card?tab=readme-ov-file#example-7---make-the-padding-smaller-around-the-artwork-of-the-thumbnails-in-the-favorites-section


---
PunxaPhil
[![image](https://github.com/user-attachments/assets/cb2e240e-f9ca-4900-a425-b8089216c1ee)](https://patreon.com/PunxaPhil) [![image](https://github.com/johanfrick/custom-sonos-card/assets/26582898/9bebc1f6-6bda-4cbd-b596-50d3d2f712de)](https://www.buymeacoffee.com/punxaphil)
