### ISSUE TITLE
Custom Favorites with similar titles

### ISSUE THREAD

**Issue by Justbob56** [punxaphil/custom-sonos-card#561]
I have some Custom Favorites that have similar titles and also have a colon in the title. When attempting to display artwork for these Custom Favorites, only the first image is used for both titles even though two different images are referenced.

For instance: 

customFavoriteThumbnails:
  Bad Company: /local/images/bad%20company.jpg
  From A Room Volume 1: /local/images/from_a_room_vol_1.jpg
  From A Room Volume 2: /local/images/from_a_room_vol_2.jpg

Both titles that begin with From A Room have a colon as in "From A Room: Volume 1"

Only the first image is displayed for both references.

Is it possible to somehow escape the colon in the title so it isn't seen as the end of the yaml statement?
I've tried encapsulating the title and the image url but nothing seems to work.

**Comment by punxaphil** [comment]
Thanks for reporting! Please try this release: https://github.com/punxaphil/custom-sonos-card/releases/tag/v8.5.3


---
PunxaPhil
[![image](https://github.com/user-attachments/assets/cb2e240e-f9ca-4900-a425-b8089216c1ee)](https://patreon.com/PunxaPhil) [![image](https://github.com/johanfrick/custom-sonos-card/assets/26582898/9bebc1f6-6bda-4cbd-b596-50d3d2f712de)](https://www.buymeacoffee.com/punxaphil)
