### ISSUE TITLE
Sonos Queue - Text Size (Card Mod)

### ISSUE THREAD

**Issue by psjnr84** [punxaphil/custom-sonos-card#569]
Hi Team,

Are you able to tell me what component of card mod styling I need to use to adjust the text size of the Sonos Queue entries?

Apologies if this is not the area to post this request, but I couldn’t find any examples in the user manual which would suggest how this could be achieved.

Any hints would be welcome :-)

**Comment by suxlala** [comment]
You can style this element with the following:
Original value is 1.1rem
`
card_mod:
  style:
     sonos-queue$ sonos-media-row$: |  
        .title {
          font-size: 1.5rem !important;
        }
`

**Comment by psjnr84** [comment]
> You can style this element with the following: Original value is 1.1rem
> 
> `card_mod: style: sonos-queue$ sonos-media-row$: | .title { font-size: 1.5rem !important; }`
> 
> The above puts the code in one row. It should be arranged like this, but with correct indentations: card_mod: style: sonos-queue$ sonos-media-row$: | .title { font-size: 1.5rem !important; }

Works a treat - thank you for the suggestion. Helps to render it better on a tablet that’s wall mounted.

**Comment by Vansmak** [comment]
What about the option to limit the amount of queue showed? When you have a long queue it makes that section much longer and you have to scroll all the way to the bottom to see the section icons

**Comment by suxlala** [comment]
> What about the option to limit the amount of queue showed? When you have a long queue it makes that section much longer and you have to scroll all the way to the bottom to see the section icons

Great idea, indeed!
Until it gets implemented in the card, you can achieve this with card_mod:

`              sonos-queue$ mwc-list$: |
                .mdc-deprecated-list {
                  max-height: 600px !important;
                }  `

**Comment by suxlala** [comment]
This is how it is inserted in my config - this code snippet is appended to the last item.
![IMG_8920](https://github.com/user-attachments/assets/6865b520-02ce-4782-9aa9-661274973c37)
You can change the card's max height in queue view by changing the 600px value. The list will remain scrollable.

**Comment by psjnr84** [comment]
As long as you have a width and height percentage set for the card, you can control the amount of records you see in the queue.

when I used to have height set to auto, it would allow the queue to expand to its full length which caused issues on a tablet presentation.

It’s a great bit of development that’s been done by the guys here on this card and if the team who developed the Spotify integration could extend that functionality using the Spotify Search API service to include a search functionality which could be adapted into this card allowing playback via these speakers, I could ditch the Spotify app completely and just live fully in the HA environment without exiting.

Here’s hoping it comes eventually..

**Comment by punxaphil** [comment]
Yes, fully correct @psjnr84 :
@suxlala @Vansmak  I don't recommend you to set height to `auto`
