### ISSUE TITLE
Sonos Favorites dont have images ... expired cert ? 

### ISSUE THREAD

**Issue by johntdyer** [punxaphil/custom-sonos-card#60]
**Checklist:**

- [X ] I updated to the latest version available
- [ X] I cleared the cache of my browser

5.1

**Last working release (if known):**
n/a

**Browser and Operating System:**
chrome

**Description of problem:**

So none of my Sonos favorites via SiriusXM have images.  It appears they are being fetched from a domain with an invalid cert.  I am just unsure where that domain gets defined .. 

```
pri.art.prod.streaming.siriusxm.com/images/chan/b7/dc2e55-e9b1-2cde-5951-90ac2c8ce042.png:1          GET https://pri.art.prod.streaming.siriusxm.com/images/chan/b7/dc2e55-e9b1-2cde-5951-90ac2c8ce042.png net::ERR_CERT_COMMON_NAME_INVALID
pri.art.prod.streaming.siriusxm.com/images/chan/4b/3e6e7b-0288-3bee-40a4-5966fb5f54db.png:1          GET https://pri.art.prod.streaming.siriusxm.com/images/chan/4b/3e6e7b-0288-3bee-40a4-5966fb5f54db.png net::ERR_CERT_COMMON_NAME_INVALID
pri.art.prod.streaming.siriusxm.com/images/chan/4a/2d9e0d-1601-59e0-2290-94f06402b363.png:1          GET https://pri.art.prod.streaming.siriusxm.com/images/chan/4a/2d9e0d-1601-59e0-2290-94f06402b363.png net::ERR_CERT_COMMON_NAME_INVALID
pri.art.prod.streaming.siriusxm.com/images/chan/1b/1bd10a-3974-beff-f686-955393dba097.png:1          GET https://pri.art.prod.streaming.siriusxm.com/images/chan/1b/1bd10a-3974-beff-f686-955393dba097.png net::ERR_CERT_COMMON_NAME_INVALID
pri.art.prod.streaming.siriusxm.com/images/channel/20180725/primecountry-1-17-00-320x320.png:1          GET https://pri.art.prod.streaming.siriusxm.com/images/channel/20180725/primecountry-1-17-00-320x320.png net::ERR_CERT_COMMON_NAME_INVALID
pri.art.prod.streaming.siriusxm.com/images/chan/84/34c993-f465-df36-5f00-3ac9152bf428.png:1          GET https://pri.art.prod.streaming.siriusxm.com/images/chan/84/34c993-f465-df36-5f00-3ac9152bf428.png net::ERR_CERT_COMMON_NAME_INVALID
custom-sonos-card.js?v=1.0:286 Sonos Card: layout.favorites configuration is deprecated. Please use layout.mediaBrowser instead.
custom-sonos-card.js?v=1.0:286 Sonos Card: layout.favorite configuration is deprecated. Please use layout.mediaItem instead.
```

when I goto the SiriusXM web player they appear to be fetching images from this CDN

```
https://siriusxm-art-dd.akamaized.net/images/chan/70/2f9d1c-36fc-fd2e-7a1d-18b3761e3545.png?width=160&height=120&preserveAspect=true
```

I know there is nothing you can do about Sirius letting their cert expire, just curious where the domain `pri.art.prod.streaming.siriusxm.com` gets pulled in from and if there is anythign I can do to get past the issue for my personal use ? 

Thanks !

**Comment by johanfrick** [comment]
I’m afraid I won’t act on this with the given info. I can only draw the conclusion that the problems you see are not specific to this card.

**Comment by johanfrick** [comment]
@johntdyer 
I realise now this is a bug the code. There was an automatic replace of http to https. I've disabled that behaviour now (it can be enabled with the config setting `replaceHttpWithHttpsForThumbnails`).

Please try it out in this beta and let me know how it works.

[v7-alpha-2](https://github.com/johanfrick/custom-sonos-card/releases/tag/v7-alpha-2)

**Comment by punxaphil** [comment]
Fixed in https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.0.0
